### ISSUE TITLE
一个人能否在同一商户多家商店里拥有雇员身份

### ISSUE THREAD

**Issue by puttin** [extensivepro/expro-future-test#102]
我认为是可以的, 原因是:
1. 作为业主, 我理应可以登录所有商店进行管理, 而登陆进一个商店在POS客户端需要有个雇员(EPEmploye)身份
2. 雇员在现实世界也是可以在多家商店同时存在的, 比如一个人身兼数家店的店长身份

不过在`离线进销存`的版本中只有一个商户一个商店这种问题还没有什么影响, 因为只有一家店

**Comment by guanbo** [comment]
- 在线版本将会以role的身份来划分权限。届时owner将会具有商户范围内最高的权限。
- 会引入店长角色，在店铺范围内享有管理权限。

@chenshun @coderhaoxin FYI
