### ISSUE TITLE
左下角账号设置中修改密码无效。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#11]
点击进入`账号设置`中的`修改密码`，这个`修改密码`界面与高保真有很大不同，并且修改之后并没有实际效果，即仍然是修改之前的密码。

**Comment by puttin** [comment]
这里是修改的EPUser的密码 所以目前没有地方使用到
登陆页面使用的是雇员(EPEmploye)的密码 所以要修改登录密码需要业主登陆后在雇员详情处修改
@guanbo @chenshun

**Comment by guanbo** [comment]
把这里的密码调整为修改employe密码吧，否则会引起用户的误解。后面我们在上线User相关的系统的适合再设计User密码的环节。

**Comment by puttin** [comment]
那完全可以把这个按钮现在版本隐藏掉 修改登录密码就在雇员那里修改

在 2013年6月21日星期五，guanbo 写道：

> 把这里的密码调整为修改employe密码吧，否则会引起用户的误解。后面我们在上线User相关的系统的适合再设计User密码的环节。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/extensivepro/expro-future-test/issues/11#issuecomment-19821044
> .

## 

Sent from Mobile Gmail

**Comment by guanbo** [comment]
可以
