### ISSUE TITLE
商户商店雇员云端同步

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#113]
- 新建雇员，保存本地后同步
  - 在本地建立变更记录。
  - 联网时同步到云端，成功后清除同步记录
  - 离线时候不做操作，等待手动或自动同步
- 更新过雇员信息后，保存本地
  - 建立变更记录
  - 联网时同步云端，成功后清除记录。

**Comment by puttin** [comment]
相关 https://github.com/extensivepro/expropos/issues/124

**Comment by guanbo** [comment]
- [x] 新增雇员以后没有自动上传到服务器
- [x] 更新雇员信息后没有自动上传
- [x] 新增商品没有自动上传服务器
- [x] 删除的商品在同步以后还能展现在商品列表

**Comment by guanbo** [comment]
Fixed：all of above in  e524ad79d0cd57dbbc8789be98dc1cbdf9523b80
