### ISSUE TITLE
商户交易云端同步

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#114]
- 新建交易，保存本地。
  - 本地建立变更记录
  - 联网时同步到云端
  - 同步成功后清除变更记录

**Comment by chenshun** [comment]
重新下载的POS，每次同步之后，交易流水号都会从`1`开始计算，使交易流水号重复

**Comment by guanbo** [comment]
Fixed: 流水单号调整为机器码+机器唯一的流水号
