### ISSUE TITLE
关于“销售商品汇总表”与“销售流水记录”中商品价格的显示

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#116]
`销售商品汇总表`中的`销售额`与`销售流水记录`中的`金额`显示的都是商品原价，即使当商品经过打折销售后仍显示原价，既然是`销售额`，我认为显示商品当时销售的价格比较合理,这样的话，在看列表进行对账的时候就不会显得矛盾，因为跟`付款流水记录`中的`付款金额`相符合。

**Comment by guanbo** [comment]
@puttin 
- `销售流水`调整为成交价。
  @chenshun 
- `销售商品汇总表` `销售额`是汇总数据。

**Comment by chenshun** [comment]
`销售流水`中的`成交金额`与实际不同，显示的仍然是原价
