### ISSUE TITLE
商店界面，添加的商品、会员或雇员等不可以删除。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#12]
建议给这些可供添加的信息加入删除功能，增加可操作性。其他都POS例如添加的商品就可以删除。

**Comment by guanbo** [comment]
因为考虑到数据关联的问题，我们现在对于上述实体采用的是状态区分，例如商品我们可以选择下架。当某商品可能有它的SKU和交易记录等，如果删除了商品，将会影响到他们的数据完整性。
