### ISSUE TITLE
建议“商品详情”中的"库存“加入编辑功能，这样同一型号的商品卖完了可以直接补充

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#120]
现在的情况是假设某种型号的商品库存没有了，不能补充它的数量，而是要重新添加一个商品库存，如果是一模一样的商品，我只想补充他的数量，不应该再添加一个商品库存。

**Comment by guanbo** [comment]
库存是不可以编辑的，到是可以加入同型产品SKU新增。
