### ISSUE TITLE
有的时候显示着会员名，但是在销售结算时却不能选择“储值消费”。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#129]
### 步骤
1. 先点击`选择会员`，输入会员编码，`确认`
2. 点击`选择会员`，切换到会员状态，点击`销售`
3. 输入商品编码选择销售商品，点击`结算`
4. 点击`现金付款`，切换到`会员储值`
### 结果

可以看到左边显示着会员名，却无法切换到`会员储值`
### 期望

目前的情况是，输入会员编码后，点击例如`对账`、`流水`这些标签按钮，再回到`销售`时，结算的时候无法选择`会员储值`，需要重新点击会员名才可以选择`会员储值`，能否在有会员名显示的情况下可直接点击到`会员储值`。

**Comment by guanbo** [comment]
Fixed @： 8170c3eb122f8c59073c97451af4dd04c034b959
