### ISSUE TITLE
收银界面，销售的结算总是出错

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#13]
进入收银界面，点击`销售`——选择几样商品——点击`结算`——点击`折扣比率`——输入一个`折扣比率`例如`95`——点击`确认`。出现的结果与应收价格的95%不相等，实际上计算出的是减去95所得数字。

**Comment by guanbo** [comment]
@chenshun 可以采用markdown形式报bug，例如：

``` markdown
### 步骤
1. `销售`
2. 录入若干商品，`结算`
3. `折扣比率` 95

### 预期
应收账款为总计金额的95%

### 现象
总计金额-95.
```

### 步骤
1. `销售`
2. 录入若干商品，`结算`
3. `折扣比率` 95

### 预期

应收账款为总计金额的95%

### 现象

总计金额-95.

**Comment by chenshun** [comment]
OK
