### ISSUE TITLE
当收银界面中的现金收支过大，则销售日报表信息显示错误

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#130]
### 步骤
1. 收银界面，点击`充值`，输入会员编码`确认`
2. 点击`选择会员`切换到会员界面
3. 输入较大的充值金额，例如`200000000`，`确认`
4. 点击`结算`，输入金额，`确认`
5. 点击`结算`
6. 切换到管理界面
### 结果

可以看到，`销售日报表`中的信息显示存在明显的错误，金额都变成了负数
### 期望

显示正常

**Comment by puttin** [comment]
@chenshun @guanbo 如何控制不允许大额充值, 有没有什么好的建议?

我的想法
1. 不允许点击 `结算` 按钮?

**Comment by guanbo** [comment]
- 不能限制用用户充值，除了到输入上限无法在计算器显示。
- 管理界面要做的是在金额显示上带上单位，例如30000，显示3万，以此类推。原则是显示字数是固定的。

**Comment by puttin** [comment]
@chenshun 现在好像没有这个问题了
