### ISSUE TITLE
销售结算时，如果对商品的单价、数量进行编辑，则后续操作无法完成

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#133]
### 步骤
1. 点击`销售`，输入商品编码，选择销售商品
2. 点击`结算`
3. 选中商品的`单价`或`数量`，并对其进行调整，例如原来`5000`调整为`4000`，点击`确认`
4. 输入付款金额，进行付款
### 结果

调整好价格后，无法输入付款金额，即使点击`现金付款`，输入任意数字都会跳出选择商品时的悬浮窗，影响结账。
### 期望

调整过价格后仍可继续付款。

**Comment by guanbo** [comment]
### 计划

调整在结算时不可以修改单价和数量。
