### ISSUE TITLE
销售结算完成后，点击商品的价格或数量，对其修改点击确认出现闪退

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#134]
### 步骤
1. 点击`销售`，输入商品编码选择销售商品
2. 点击`结算`，输入金额点击`确认`
3. 点击`结算`
4. 点选交易单中的`单价`或`数量`，输入数字对其进行修改，点击`确认`
### 结果

程序闪退
### 期望

修改无效，程序不会退出

**Comment by guanbo** [comment]
已经在 #133 的commit https://github.com/extensivepro/expropos/commit/fc3dc5387e105e54c81ab2e9482d4dca0b5c0a2a 中修改完成
