### ISSUE TITLE
收银过程中，如果有会员名显示，就会认定是该会员进行的消费。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#135]
当进行过会员充值或是会员储值消费后，会员身份仍然存在于收银界面，同时他又不影响接下来的非会员销售结算，这样就会造成：使用者在收银的过程中，忽略掉去重置这个会员身份，导致之后的消费记录显示都是该会员，而实际情况并非如此。

**Comment by guanbo** [comment]
调整为操作完以后清除会员身份
