### ISSUE TITLE
会员充值完成后，交易账单中的信息错误

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#137]
### 步骤
1.  点击`充值`
2.  输入会员编码点击`确认`
3.  点击`选择会员`
4.  输入充值金额，点击`确认`
5.  点击`结算`，输入付款金额，`确认`、`结算`
### 结果

可以看到交易账单中的`充前余额`变为`0`，即使有余额显示也为`0`
### 期望

显示的`充前余额`与会员账户余额一致

**Comment by chenshun** [comment]
该BUG仍然存在。

**Comment by guanbo** [comment]
持续集成服务Jenkins的问题，没有自动发布版本。请下载今天发布的版本，再确认。
