### ISSUE TITLE
新建雇员进行过销售商品后，回到管理界面，雇员列表会多出一条一模一样的雇员信息。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#139]
### 步骤
1. 点击`雇员`
2. 点击`+`，根据系统步骤新增一个雇员
3. 登出管理界面，选择新增加的雇员进入收银界面
4. 点击`销售`，完成一次销售商品
5. 登出收银界面，进入管理界面
6. 点击`雇员`，查看雇员列表
### 结果

可以看到雇员列表里有两条该雇员信息
### 期望

显示正常

**Comment by puttin** [comment]
不用完成销售也会多一条

**Comment by puttin** [comment]
发生的原因尚不明确, 通过修改读取数据的方式修复
