### ISSUE TITLE
关于收银界面，销售结算中的取消按钮。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#14]
当输入出错，点击`取消`，再重新点击`结算`，进入的仍然是之前操作出错的界面，希望点击`取消`后重新点击`结算`可以进入到一个新的结算页面以便重新输入正确的数字。

**Comment by guanbo** [comment]
@xiaoyuxiong @MengWei 针对 @chenshun 的建议，你以使用者的角度是否赞同。

我设计的时候考虑的是当结算的时候需要补充添加一些商品的情况，回来的时候我以前的结算还在。

**Comment by guanbo** [comment]
计划修改为将取消的结算，放弃当前的账单。

**Comment by guanbo** [comment]
fixed #14 in 1cca94792a9fea31708449b2814a6f6cec11cea4
