### ISSUE TITLE
会员储值消费，结算完成后的账单有误

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#140]
### 步骤
1. 点击`销售`，输入商品编码选择销售商品
2. 点击`选择会员`，输入会员号点击`确认`
3. 再次点击`选择会员`，点击`结算`
4. 点击`现金付款`切换到`会员储值`
5. 输入足够的金额，点击`确认`
6. 点击结算
### 结果

可以看到账单中的`找零`实际上是结算时候的`会员储值`
### 期望

显示正确

**Comment by guanbo** [comment]
没有复现，可能已经在 #137 中修改掉
