### ISSUE TITLE
退货过程中，点击取消回到的账单显示有误

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#141]
### 步骤
1. 点击`流水`
2. 输入一个交易流水号，点击`确认`
3. 选中账单中的商品，点击`退货`
4. 点击`取消`，然后查看交易账单
### 结果

可以看到，账单中原本是`实收金额`显示为`已退金额`
### 期望

点击`取消`回退出的账单与原来账单一致

**Comment by chenshun** [comment]
步骤进行到第三步的时候，是调整退货的界面，实际上还并没有退货，此时显示`已退金额`感觉不恰当。

**Comment by guanbo** [comment]
- 已退金额->应退金额
- 取消后改为实收金额

**Comment by chenshun** [comment]
使得销售过程中，原本的`应收金额`也变成了`实收金额`

> - 取消后改为实收金额
