### ISSUE TITLE
管理界面的设置中可以查看云端存储情况

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#146]
[原型102-setting](http://invis.io/G2FRITFK)
- 空间占用情况采用异步的获取的方式
- 在没有获取进行中用动画表示
- 在获取失败的时候文字提示“无法获取空间情况”

**Comment by haoxins** [comment]
如何统计占用的存储空间?

**Comment by guanbo** [comment]
@coderhaoxin #147 && [Issue #200: 商户云端存储空间容量实现](https://github.com/extensivepro/expro-future/issues/200)

**Comment by haoxins** [comment]
几个issue递归引用，内容不差不多么？我读取商户所有的数据然后再统计容量?这代价比较大吧?

**Comment by guanbo** [comment]
- 考虑在接口中利用事件机制做增量统计
- 讨论自己问题最好在自己的Issue中，你服务端统计的方式与客户端无关

**Comment by guanbo** [comment]
策略调整为按终端收费。
