### ISSUE TITLE
获取商户云存储空间统计接口设计

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#147]
- GET /商户云端空间
  - [ ] 商户云端存储空间容量上限
  - [ ] 商户云端存储空间有效期
  - [ ] 商户云端存储空间占用容量
- 参考 #146

**Comment by haoxins** [comment]
@guanbo 请不要循环引用，本人脑子不太好使，很容易被绕昏

**Comment by guanbo** [comment]
策略调整为按终端收费。
