### ISSUE TITLE
关于收银界面的销售结算，如果先进行折扣比率则不能继续进行折扣金额的计算

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#15]
点击`销售`——选择几样商品——点击`结算`——点击`折扣比率`——输入一个`折扣比率`例如`95`——点击`确认`——再点击`折扣金额`——输入某一数字——点击`确认`没有反应。打完折之后应该可以继续进行金额折扣，两者先后操作应该不影响

**Comment by guanbo** [comment]
目前考虑的设计的不想搞复杂，所有现在结算折扣，比率或金额只选其一。将来如果是商户普遍有这样的需求，我们在调整。
