### ISSUE TITLE
商户账单的云端同步

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#156]
- 新建账单，保存本地。
  - 本地建立变更记录
  - 联网时同步到云端
  - 同步成功后清除变更记录

**Comment by chenshun** [comment]
账单同步获取过一次，之后再同步，交易账单又消失了

**Comment by guanbo** [comment]
3eadb057482be8a0954b45b6bb746ec5d92b9f7d 修复

**Comment by guanbo** [comment]
同步出现问题
