### ISSUE TITLE
关于商店详情中的“暂停营业”。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#157]
在商店详情中，商店的`营业`状态可以切换成`暂停营业`，但是切换后商店内的商品仍然可以继续销售。

**Comment by guanbo** [comment]
@puttin 在登陆到收银界面的时候检查时候发暂停营业。如果暂停营业中，提示用户并要求其更改。

**Comment by puttin** [comment]
@chenshun @guanbo 
- 或者干脆在在线同步完成之前把该功能禁用掉吧 因为当前不能新增商户商店 而改为暂停营业后理应就不能使用才对
- 或者改为不允许收银员登陆 提示(alert)暂停营业 业主登陆提示(alert)修改暂停营业
