### ISSUE TITLE
产品能够上传照片

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#158]
- 在新增产品或编辑产品的时候能够上传产品的照片
- 这样可以在新增库存或者未来的专卖店形式的版本中陈列出照片

**Comment by puttin** [comment]
@guanbo CoreData结构部分如何处理

**Comment by guanbo** [comment]
你自己设计，我会review的

**Comment by puttin** [comment]
@guanbo 应该对应到库存(SKU)上 而不是 商品(item)上

**Comment by guanbo** [comment]
为什么是SKU而不是item？或者两者都有

**Comment by guanbo** [comment]
调整到 #364 中实现
