### ISSUE TITLE
商品中要有单位名称

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#159]
- 商品中新增单位字段，类型String。
- 同种商品的不同单位作为两种商品存在。

**Comment by puttin** [comment]
> 同种商品的不同单位作为两种商品存在

不是很明白

**Comment by guanbo** [comment]
比如茶叶：龙井有1盒、1包等，每种单位就是一种商品

**Comment by puttin** [comment]
那完全可以用不同库存来区别啊
商品是龙井
- 库存1: 一盒
- 库存2: 一包

**Comment by guanbo** [comment]
也可以
