### ISSUE TITLE
收银界面，对账账单时间输入以及“打印”问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#16]
对账账单日期显示到具体日期后的小时、分钟，但是输入日期如果输入到具体的小时、分钟，点击`确认`则没有反应。 并且对账账单中的`打印`一直都是灰色，在没有点击打印之前应该和高保真中一样为有色。
具体步骤：点击`开始日期`——输入某一日期`201212121010`——点击`确认`

**Comment by guanbo** [comment]
- 对账单输入将保证到分钟。
- 打印因为还没用研究也没用，放到后云端版本的里程碑实现参见 #21。同时打印的启用是在已经生成了对账单以后，否则不可以启用。
