### ISSUE TITLE
PassPro会员开放接口实现

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#161]
- 实现开放接口中定义的接口
- 由于开放接口是需要公布接口的，所以在安全性测试上一定要加强。
- 考虑很多第三方系统可能不会与我主动对接，我们可以需要利用一些脚本帮助下将对方的数据一次性导入到我们系统中，所以可以在实现的时候考虑编写一些导入模版。

**Comment by haoxins** [comment]
个人觉得开放接口应该在下一个版本
这个比较复杂、工作量大
最好在有了相关客户的需求后，综合客户的需求实现。如果一开始就弄的话，很有可能后期大量改动。

**Comment by guanbo** [comment]
我们自己先要有充分的考虑，否则你一片空白怎么和客户对接。这块也是客户真实反馈出来的需求，虽然不一定马上就做完，但也要在很短的时间内上线。

**Comment by haoxins** [comment]
- 那最好分个先后：进销存、会员、其他
- 最麻烦的是各种不同商户商品数据差异很大，很难搞一个统一的数据接口

**Comment by guanbo** [comment]
> 那最好分个先后：进销存、会员、其他

这块仅考虑会员，PassPro的接口。

> 最麻烦的是各种不同商户商品数据差异很大，很难搞一个统一的数据接口

难道没眼看到 #160 中“以我为主”，自己要有一套标准才好，否则我们适应别人的东西，我们内部的应用怎么搞。

**Comment by haoxins** [comment]
但是我们的标准也要考虑到不同的商户

**Comment by guanbo** [comment]
对于商户的具体情况要具体对待：
- 普遍性的需求要整个进来
- 比较特别的需求可以先不考了
