### ISSUE TITLE
泛商汇进销存系统的PC版本实现

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#162]
- 将目前POS的主要功能放在PC端实现。
- PC端要支持离线模式版本，可以联网以后将数据同步到远程。

**Comment by haoxins** [comment]
PC端指的是web版？还是客户端？
这个是我找到的用于web端离线存储的，初步验证没问题
所谓初步验真，就是我还没验证间隔时间超过一天会不会数据丢失
https://github.com/daleharvey/pouchdb

**Comment by guanbo** [comment]
可以考虑调研在客户window系统中部署node.js和mongodb，先将数据存本地数据库。联网后同步两端数据库。

**Comment by haoxins** [comment]
- 如果要用户自己起服务会不会太麻烦，用户不会愿意吧
- 我觉得干脆第一版就不支持离线，毕竟有了客户需求后再视情况定(就我家附近商户来看，不联网、断网几乎很少出现)
- 如果一开始就搞离线支持会大大延迟发布时期，还不如先不支持，尽早发布看看客户反应

**Comment by guanbo** [comment]
可以，先实现在线版本

**Comment by haoxins** [comment]
求原型
