### ISSUE TITLE
pos的建议

### ISSUE THREAD

**Issue by haoxins** [extensivepro/expro-future-test#163]
### 主界面
- 一开始找不到怎么完成一笔交易，（左侧栏的各个项目的命名向导性不强）
- 添加交易应该有一个明显的入口，不应该在：销售流水记录——>  `+`  ，主要功能的入口太不明显了
- 左侧的导航栏，有的可以点击`+`新增，有的不可以，在未进入之前没有明显的区分，同样向导性不足（比如：销售流水记录就不该夹在另外三个中间，核心功能被藏起来了）
- 把销售流水记录改为：`销售`，放到`管理`
- 把库存流水记录改为：`库存`，放到`管理`
- 把`库存汇总表`放到上面，取消`库存`

**Comment by haoxins** [comment]
### 进入添加交易后(就是长得像`计算器`的那个界面)
- 不知道怎么退出
- 功能区分度不高：充值、交易、退货等，初次使用的话完全弄不明白
- 那个绿色的`C`按钮，一般人不会知道那是`cancel`
- 对账是干嘛用的？
- 为什么是流水——>退货，而不是直接退货。我们不应该把自己的开发流程体现在用户使用上，使用应该一步到位
- 为什么在这里还有个`库存`选项，干什么用的
- 点击`充值`后，必须点一下`选择会员`才能切换到`销售`等其他选项，一开始我弄了半天不知道怎么退出去

**Comment by haoxins** [comment]
### 同样是在`计算器`界面下
- 那个`输入交易流水号`之类的顶部的文字到底能不能点击？
- 我是点击`新业主`，那个顶部的文字退出此界面的，这是什么意思？

**Comment by haoxins** [comment]
- 作为一个初次使用的客户，我不会知道：需要添加商品——再添加库存——然后才能销售
- 对于助记码、编码之类的东西应该有人性化的提示，否则会搞混用户，比如：助记码：输入方便您查询的编号或字符，而不是：输入助记码。 **用户会有个错觉** ，助记码在商品的什么地方，我怎么没找到。

**Comment by haoxins** [comment]
- 我在`计算器`界面下不知道怎么添加交易商品
- 我不知道`计算器`左下角的纸条一样的东西是用来显示的，还是可以点击编辑的

**Comment by haoxins** [comment]
我知道`cashier employee`的权限，但是普通用户不知道，
`业主`或者`owner employee`有两个主界面
`cashier employee`只有`计算器界面`，
这两者的功能重复度和区别度如何？反正我一直到现在都没明白(已经快2小时了)

**Comment by haoxins** [comment]
### 两个小时过去了，我没有成功完成一次交易、或者一次退货、或者一次充值 :1234:

**Comment by guanbo** [comment]
@coderhaoxin 请尝试新的版本
@chenshun 请跟踪反馈
