### ISSUE TITLE
促销优惠管理

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#167]
在管理界面中可以促销优惠活动的管理  
- 标题：< 64字节  
- 内容：< 50000字节  
- 条件：`无`、`一次消费满额`、 `累计消费满额`、 `累计消费满次`  
- 形式：`折扣`、 `抵用券`、 `积分数额奖励`、 `积分倍数奖励`、 `礼品`、 `会员储值返现`、 `现场减金额`  
- 对象：`顾客`、 `会员`、 `会员等级要求`  
- 时间：`开始时间`、 `结束时间`

**Comment by chenshun** [comment]
优惠活动中的`条件`是必选项吗？很多地方只要是会员就可以享受优惠，不需要满足任何条件。

**Comment by guanbo** [comment]
活动门槛条件和活动适用对象范围的情况，这是两个概念。虽然本质上都是限制措施。

我会增加一个`无条件`的情况。

**Comment by chenshun** [comment]
`形式`在原型中要不要具体体现出来？例如`折扣`要让用户在操作的时候可以输入具体数字，又或者`积分倍数奖励`用户在操作的时候可以输入具体的倍数等等，还是只需要有可供用户选择的`形式`就可以了？

**Comment by guanbo** [comment]
要全部体现出来，你也可以补充。在最后要留一个其他，给用户输入字符串。

**Comment by chenshun** [comment]
如果是针对具体商品展开的促销活动，是否应该在条件中加入`指定商品`的情况。

**Comment by guanbo** [comment]
可以指定商品，但这个做为可选项。

**Comment by guanbo** [comment]
分解 #174
