### ISSUE TITLE
雇员详情中，编辑的雇员工号如果过长保存时会出现变化。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#168]
### 步骤
1. 点击`雇员`，点击`>`，进入雇员详情
2. 点击`编辑`，修改`工号`输入`123456789123456789`
3. 点击`保存`
### 结果

可以看到原本输入的工号变成了一串其他数字。
### 期望

对雇员的`工号`加入长度限制，避免类似错误发生。

**Comment by puttin** [comment]
@guanbo 
在https://github.com/extensivepro/expro-future-test/issues/165 中提及

> 员工工号可以输入字母，有单位是在员工编号中使用了字母

现在CoreData结构中工号是Integer 64

改成string?

**Comment by guanbo** [comment]
改String

**Comment by puttin** [comment]
@guanbo 但改成string后新增雇员时候就不好自增了 那就取消自增了?

**Comment by guanbo** [comment]
还要给提示最后加入员工的工号，方便用户。

**Comment by puttin** [comment]
已由 @guanbo 在 https://github.com/extensivepro/expropos/commit/cb7636052142381199db29a55c118ec7b77e02c8 中修复
