### ISSUE TITLE
新建商品的“单位”不得为空，但是在商品详情中编辑时却可以为空，相互矛盾

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#169]
应该在商品详情中也加入商品单位不得为空的限制。

**Comment by puttin** [comment]
@guanbo  新建商品的"单位"是否必须填?

**Comment by guanbo** [comment]
必填，但默认以”件“为单位，帮用户填好。

**Comment by puttin** [comment]
@guanbo 但因为实际是附加到品名后面的 所以在详情里面编辑时可以去掉 无法保证 商品中有对应的单位

**Comment by guanbo** [comment]
在编辑的时候，没有”单位“项目。直接在品名中显示。

**Comment by puttin** [comment]
@guanbo 你没懂我意思 编辑商品详情的时候 因为没有单位这一栏 直接显示在品名中 所以即使创建商品("iPhone")的时候填写了单位 比如"件" 实际品名是"iPhone 件" @chenshun 的意思是用户可以在编辑商品的时候把件删除了

**Comment by guanbo** [comment]
单位就放在品名中，由客户自己掌握。如果客户对这块反应较大，我们再做调整。
