### ISSUE TITLE
建议对收银界面中点击“选择会员”出现的界面做出一些调整。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#171]
点击`选择会员`，左边出现一个空的会员资料表单，这个界面完全没有作用。建议把此时的空表单替换成类似`库存`列表一样的`会员`列表，列表里显示出`会员编号`、`会员姓名`、`手机号`、`储值余额`这些重要的信息，输入会员编码和手机号可以筛选左边列表中的会员，同时也可以直接点击选中相应会员。选中会员后跳转出会员详情表单。

**Comment by guanbo** [comment]
这块是出于隐私考虑，不能将会员信息罗列在列表中。只有输入的手机号和会员编号正确的时候才能显示在会员信息。

**Comment by chenshun** [comment]
明白
