### ISSUE TITLE
新增库存功能太深用户到达率低

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#172]
- 从友盟的数据漏斗分析来看，新增库存的功能到达为0。分析原因可能有以下可能
  - 功能路径太长（4步），用户放弃了。
  - 功能的引导性不强，不能给用户以明确指示。
  - 用户可能还没用明白`商品`->`SKU`的体系。
- 重新设计SKU交互部分的原型：
  - 调整商品详情展示，不在以右侧滑出的形式展现，而是以modal的方式独占屏幕。
  - 在商品详细界面用突出的方式引导客户，可以在这个界面新增SKU。

**Comment by chenshun** [comment]
如果我是一名店长，店里进了一批商品，我需要记录下来，这时候的逻辑应该是记录下商品的名字、型号、价格、数量以及日期，这样就直接有个该商品的库存，有了之后我再选择什么时候出售，售价定多少。而我们系统中的逻辑是要先添加该类商品，再去针对这个商品添加不同型号的库存。这样有两个缺点：
-  绕了一个弯，用户刚接触的时候不会明白这个逻辑，所以他们新建商品之后没有去添加`SKU`
-  统计下来的数据忽略了用户进货花费的金额，支出的钱也是很重要的信息，有必要为用户统计下来。  

能否把不同型号的商品看成不同的商品，把商品分成两大类，`上架`和`未上架`。用户新增的商品在`未上架`的列表里，然后选择`上架`的时候再设定出售的价格，这样就像是进货的到仓库，再从仓库拿东区去卖，逻辑简单，切合实际。

**Comment by chenshun** [comment]
系统中从`库存流水记录`列表新增库存，这里新增的是出售商品的库存，也就是上架多少商品，出售价格是多少。进销存应该尽量体现出进货和销货的细节。而实际并没有把我进货这一块的数据统计出来。我的想法是取消掉`库存流水记录`列表中的`新增库存`功能。用户在新增商品的时候不是在选择出售商品，而是在进货。完成进货之后再去选择上架商品。

**Comment by guanbo** [comment]
> 如果我是一名店长，店里进了一批商品，我需要记录下来，这时候的逻辑应该是记录下商品的名字、型号、价格、数量以及日期，这样就直接有个该商品的库存，有了之后我再选择什么时候出售，售价定多少。而我们系统中的逻辑是要先添加该类商品，再去针对这个商品添加不同型号的库存。这样有两个缺点：
> 
> 绕了一个弯，用户刚接触的时候不会明白这个逻辑，所以他们新建商品之后没有去添加SKU
> 统计下来的数据忽略了用户进货花费的金额，支出的钱也是很重要的信息，有必要为用户统计下来。
> 能否把不同型号的商品看成不同的商品，把商品分成两大类，上架和未上架。用户新增的商品在未上架的列表里，然后选择上架的时候再设定出售的价格，这样就像是进货的到仓库，再从仓库拿东区去卖，逻辑简单，切合实际。
- 把你的想法整理成时序图，比较直观。可以参考我Balsamiq Mockups原型下面的有个bussiness的目录，里面有有我以前画过的时序图你可以参考。
- 同意你的以新增SKU为主要操作逻辑，但需要梳理清楚。
- 拆分成上架和下架会多一个步骤，我想等用户反馈的情况在考虑。

> 系统中从库存流水记录列表新增库存，这里新增的是出售商品的库存，也就是上架多少商品，出售价格是多少。进销存应该尽量体现出进货和销货的细节。而实际并没有把我进货这一块的数据统计出来。我的想法是取消掉库存流水记录列表中的新增库存功能。用户在新增商品的时候不是在选择出售商品，而是在进货。完成进货之后再去选择上架商品。
- 实际上我们更多的是个销售系统，所以我在这个阶段弱化了进货管理。如果丰富起来，其实有很多东西，例如供应商等。这块我的思想是先把销售做好，由用户驱动我们去做其他部分。类似的情况还有很多，例如调库我们也没用。

**Comment by guanbo** [comment]
在下面的任务中完成
- #175 
- #176
