### ISSUE TITLE
关于免费的存储容量的设置

### ISSUE THREAD

**Issue by haoxins** [extensivepro/expro-future-test#173]
根据我们暂行的统计方式，我粗略估计下：
### 512M可以存储 **40w** 条数据，(假设每一笔交易含5件商品)。

对于一个中小型商户(对于使用我们这种设备的商户，不会是那种交易频繁的超市类商户)
如果按单天 12h \* 10 = 120 笔交易来算（加上其他商品、库存假设为：30），
### 如果后期加入图片(商品图片、活动图片等)或许可以消耗的快点。

但是：以一张图100k计，512M可存储约5240张，若：一天消耗7-8张，

**Comment by haoxins** [comment]
### 我的建议是，

暂时先不要定免费的存储空间容量，至少先让用户用上2-3个月
先储存一批用户，等我们有了一些数据后，再确定免费的存储空间容量。否则，你定512M太大，你定50M什么的用户觉得太小，毕竟用户不会直观的感受到单条数据存储是以byte计的，
普通用户不会有换算概念，他跟某些网盘服务商稍微比较下就会感觉不爽。

**Comment by guanbo** [comment]
> 暂时先不要定免费的存储空间容量，至少先让用户用上2-3个月
> 先储存一批用户，等我们有了一些数据后，再确定免费的存储空间容量。否则，你定512M太大，你定50M什么的用户觉得太小，毕竟用户不会直观的感受到单条数据存储是以byte计的，
> 普通用户不会有换算概念，他跟某些网盘服务商稍微比较下就会感觉不爽。
- 你3个月以后在跟用户说免费512M，这样会收获奇效？
- 网盘觉网盘和收银软件能一样的吗，如果你网盘能收银，你就用网盘吧？
- 512M一点都不多，图片资源你估算的太保守了，而且完全没有考虑索引空间的问题，而你的交易有没有包含bill的容量？

**Comment by haoxins** [comment]
> 你3个月以后在跟用户说免费512M，这样会收获奇效？

3个月后，根据用户使用量，确定免费容量。如果绝大多数用户3个月只用了几兆呢？

> 512M一点都不多，图片资源你估算的太保守了，而且完全没有考虑索引空间的问题，而你的交易有没有包含bill的容量？
- pos不是拿给客户看的，不是点餐类应用。业主很有可能为了节省空间根本不上传图片。
- deal包含bill

**Comment by guanbo** [comment]
数据总会增长的。你现在算得这点容量根本没有有经过验证，512M不是太多，是太少。
- 你怎么知道用户不想上传图片，POS的图片功能就是潜在客户提出来的。
- 后期的交易记录，用户和商户之间的沟通数据，都会占用空间，业务是发展的。
- 早期让用户有一种超值的体验，不是坏事。
