### ISSUE TITLE
对商品模块做出调整

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#176]
-  用户在`新增库存`的时候生成相应商品信息
-  取消了`新建商品`功能
-  商品共分为`已上架`和`未上架`两个页面
-  `商品详情`不再是右移显示，而是点击弹出详情界面

**Comment by chenshun** [comment]
详情参照[低保真](https://projects.invisionapp.com/share/J8E2OYNW#/screens/6211689?maintainScrollPosition=false)

**Comment by puttin** [comment]
@guanbo 表结构中 `商品` 无上架和下架时间, 添加?

**Comment by puttin** [comment]
由于商品详情现在是Modal的对话框 不适合继续保留以前的新增库存和滑动复制库存 在接下来的commit中初定取消

**Comment by guanbo** [comment]
同意
