### ISSUE TITLE
清除初始化数据

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#177]
用户在AppStore上反馈演示数据不可以删除，使用不方便。
- SKU和商品可以做标记删除
- 在商品和SKU流水界面的导航条居中位置加入`正常/已删除/全部`的Label，用来过滤筛选。
- 在商品和SKU界面加入列表项目编辑入口，可以方便用户做批量操作。

请出原型效果图。
PS:以后有user driven标签的表示由用户驱动的需求，需要优先考虑。

**Comment by chenshun** [comment]
做成过滤筛选得Label放在导航栏中间取代列表标题感觉不可取。因为实际操作中，用户肯定很少会去查看删除的商品和SKU，他们要满足的只是删掉他们不想显示的数据。没有必要把这么好的位置给一个不常用到的操作。
我的想法是在列表最右侧放一个类似书签的小图标，点击之后拉出一个小书签用来选择`正常/已删除/全部`，因为界面的整体风格就是一本账目册子。

**Comment by guanbo** [comment]
可以按你的思路先实现原型，然后在原型上讨论。

**Comment by guanbo** [comment]
@chenshun 低保真原型中的《库存流水记录》的命名成了汇总。请更正。
@puttin 请参看低保真原型中库存流水和商品中的原型尽快实现删除功能。目前Apple AppStore上对这个问题反映比较大。

**Comment by puttin** [comment]
标记删除初始数据 可以做 但是体验数据会成为垃圾数据
#228

**Comment by chenshun** [comment]
> 低保真原型中的《库存流水记录》的命名成了汇总。请更正。  

我把《库存汇总表》和《库存流水记录》调换了一下位置。

**Comment by guanbo** [comment]
> 标记删除初始数据 可以做 但是体验数据会成为垃圾数据
> #228

被标记删除的垃圾数据不会影响统计，所以无关紧要。

**Comment by puttin** [comment]
> 被标记删除的垃圾数据不会影响统计，所以无关紧要。

之后做同步的时候会不会把被删除的上传?

**Comment by puttin** [comment]
暂定无法查看标记删除的数据

@guanbo 另外标记删除商品是否应该把相关库存记录也标记删除?

**Comment by puttin** [comment]
相关:
extensivepro/expropos#141
