### ISSUE TITLE
关于管理界面各个列表导航栏中的“添加”、“搜索”和“刷新”三个按钮。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#178]
-  三个按钮的图标看上去显得较小
-  `搜索`和`刷新`靠的太近，操作的时候如果不是小心翼翼，很容易点错

**Comment by chenshun** [comment]
建议取消图标外围的小圆圈，稍微放大内部图标直接显示在导航栏中，之间间隔稍微远一点。

**Comment by guanbo** [comment]
@puttin 请联系美工解决。

**Comment by puttin** [comment]
暂时只使用了更大的图标, 希望顺带解决了 `靠的太近，操作的时候如果不是小心翼翼，很容易点错`
