### ISSUE TITLE
结算流程提示不够清晰

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#179]
以商品销售为例，点击结算按钮，进入结算页面，
1.输入付款金额， 点击确认后，提示不够清晰，不知道如何才算完成本次消费结算过程。
2.点击结算后，出现打印机选项页面，这个时候有个过程，希望出现提示过程，第一次使用以为系统假死
3.结算的时候，能否在输入完金额后，部分按钮变灰（包括那个输入金额的部分），给人比较明显的提示；

**Comment by guanbo** [comment]
@chenshun 考虑一下调整交互流程，届时我们在原型上讨论一下。

**Comment by chenshun** [comment]
>  1.输入付款金额， 点击确认后，提示不够清晰，不知道如何才算完成本次消费结算过程。

我认为结算界面需要用户注意的地方太多了，`左上角的提示`、`中间小显示屏`、`右边输入框`，用户在执行一步操作的时候没有办法兼顾三个地方，所以一步操作完成后甚至不知道刚才起到了什么作用，也就不知道接下来该如何下手，所以感觉提示不够清晰。
我建议把上面三个东西结合起来，重点在`显示屏`中表现出来。取消右边的输入框，输入直接在`显示屏`中可见，提示也放在`显示屏`中，例如点击`现金付款`，显示屏中显示`请输入付款金额`，并且有闪烁的光标，输入之后可以看到输入结果。这样提示就很强。

**Comment by guanbo** [comment]
> 我认为结算界面需要用户注意的地方太多了，左上角的提示、中间小显示屏、右边输入框，用户在执行一步操作的时候没有办法兼顾三个地方，所以一步操作完成后甚至不知道刚才起到了什么作用，也就不知道接下来该如何下手，所以感觉提示不够清晰。
> 我建议把上面三个东西结合起来，重点在显示屏中表现出来。取消右边的输入框，输入直接在显示屏中可见，提示也放在显示屏中，例如点击现金付款，显示屏中显示请输入付款金额，并且有闪烁的光标，输入之后可以看到输入结果。这样提示就很强。

之前曾考虑过类似方案，但有2个问题：
- 输入商品的时候需要有自动补齐的提示，放在放在显示区域手指的行程过长。
- 需要自定义输入框，可能会花一点时间，可以作为考虑的方案之一。

**Comment by guanbo** [comment]
界面和交互设计已经调整过，当前问题已不适用。
