### ISSUE TITLE
缺乏足够的提示

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#180]
操作过程中缺少明确的提示，由于使用的不够深入和全面，举简单的例子如下：
1.库存页面：假设输入无效的代号，测试中如10001000，只看到商品栏中无任何商品，但是无明显提示；
2.退货页面：退货后商品无标示，易造成重复无用操作；中间有打印界面，页面会呈现假死，希望能改善下，或者出现个提示什么的（例如菊花图标在转）；
3.有超卖现象存在，库存10个，可以销售11个；

**Comment by guanbo** [comment]
> 2.退货页面：退货后商品无标示，易造成重复无用操作；中间有打印界面，页面会呈现假死，希望能改善下，或者出现个提示什么的（例如菊花图标在转）；

@chenshun 请考虑调整交互设计。 

> 1.库存页面：假设输入无效的代号，测试中如10001000，只看到商品栏中无任何商品，但是无明显提示；

暂不考虑，将来会取消POS界面查库存

> 3.有超卖现象存在，库存10个，可以销售11个；

由于现在销售是不建立在库存基础上的，所以这块暂不考虑。

**Comment by chenshun** [comment]
重新调整了POS[退货流程](https://projects.invisionapp.com/d/main#/console/292578/6534895/preview)。
@puttin

**Comment by puttin** [comment]
关于新的退货流程, 请尽量多测试, 虽然我自己测了很久, 但觉得肯定还有各种坑
