### ISSUE TITLE
销售流水记录中有显示的格式错误

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#182]
在查看销售流水记录中，能看到身份为收银员进行销售的时候，记录存在排版错误，显示为重合，暂未找到形成该记录的规律，先标记。

**Comment by puttin** [comment]
@guanbo 这个一直没法重现... 我自己是没遇到过 @chenshun 好像遇到过也不知道怎么重现

**Comment by chenshun** [comment]
我没有遇到过，上次是coder发现的，但是无法重现。我找了不下于三个小时也无法重现。似乎只有在非正常操作下才会出现该bug。

**Comment by xiaoyuxiong** [comment]
我把此bug关闭，在测试、研发过程中请注意能否重现！

**Comment by guanbo** [comment]
这类问题，如果确实没法复现就打上noreproduce的标签，然后关闭。将来如果发现了规律再reopen
