### ISSUE TITLE
雇员身份不能删除？

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#183]
雇员列表中的收银员能否删除，如果删除后，该雇员的交易就如何存储和体现；不知道身份证号码是如何定义的，我试了几次，无效；无法编辑该雇员信息

**Comment by guanbo** [comment]
- 雇员不可以删除，只能离职。
- 身份证号码是按照身份证代码规则校验的，所以必须是有效身份证才可以。
