### ISSUE TITLE
收银机设置

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#184]
参考原型实现[收银机设置](http://invis.io/YEG9MD4V)
- 实现商户的管理和云同步
- 实现商店的管理和云同步

**Comment by guanbo** [comment]
相对原型，在开发中做了一些调整：
- 收银机设置页，新增了设备的UDID
- 商户设置页调整了布局，突出了商店的选择

**Comment by chenshun** [comment]
在实际操作过程中遇到两个问题：
- `收银机设置`窗口中机器信息的`代码`修改后无法保存
- `云端账户`窗口目前无法登陆，点击`注册云端账户`，程序出现闪退
