### ISSUE TITLE
商店设置管理中调整

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#185]
参考[商店管理设置](http://invis.io/G2FRITFK)中原型的调整，实现下列功能。
- 管理界面左下角显示信息变更
- 当前登陆雇员信息及其编辑
- 商店设置

**Comment by chenshun** [comment]
> Issue #227:[POS管理界面，商店设置中的“商店代码”无论怎么修改都会变为原来默认的。](https://github.com/extensivepro/expro-future-test/issues/227)
