### ISSUE TITLE
新业主中密码重置功能是否无用？

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#187]
新业主是拥有最大权限的人，此处是否提供重置密码的功能？个人觉得不应该，最多也就是重设密码，但是必须输入原密码才行！

**Comment by guanbo** [comment]
重置密码主要是考虑在忘记密码的情况重新输入密码。考虑的场景是忘记密码的人就在旁边。重置完了就直接设置自己的密码。
