### ISSUE TITLE
流水页面建议

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#188]
在流水页面中查询到相关交易的信息，不做任何操作，即转入销售或者其他页面，再次点击流水的时候，还是显示该笔交易信息，建议再次进入流水页面的时候，页面显示为空。

**Comment by puttin** [comment]
@guanbo 这是设计如此的还是bug?

**Comment by guanbo** [comment]
体验不好，所有enhancement
