### ISSUE TITLE
销售流水记录没有反应真实的消费行为

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#189]
在销售过程发生时，如果输入了现金折扣并完成交易！在后台查看销售流水记录报表时，成交金额依然显示的是原价，没有真实记录交易过程，容易引起后期盘点问题

**Comment by guanbo** [comment]
考虑在销售记录中体现折扣金额。

**Comment by puttin** [comment]
@guanbo 单独一列折扣金额还是直接扣除折扣金额显示?

**Comment by guanbo** [comment]
成交金额中体现，即扣除折扣后的实际成交金额。

**Comment by chenshun** [comment]
- 库存汇总表中的`收入`显示的不是实际成交金额，需要调整。
- 销售流水记录展开后显示的`成交金额`仍不是实际成交金额。
- 销售商品汇总表中`销售均价`与`销售额`均不是实际成交金额。
- 销售日报表中`现金消费`不是实际成交金额，需要调整。

**Comment by puttin** [comment]
1. `库存汇总表` 的 `收入` 目前的结构只能精确到账单折扣前的价格, 但包含了结算前修改的价格
2. `销售流水记录` 的`成交金额`也只能精确到折扣前的价格
3. `销售商品汇总表` 因为上述 相同原因 也只能如此
4. `销售日报表` 也是如此

如果想要精确到这件商品折扣了100元 另一件原价卖出
则需要把折扣从账单层次移到或者添加到购买的商品层次
@guanbo @chenshun

**Comment by guanbo** [comment]
- 库存汇总和销售商品汇总，保持现状
- 销售流程记录中把折扣金额和折后金额体现出来
- 销售日报也把日折扣总额体现出来

**Comment by puttin** [comment]
归纳:
- `库存汇总表` 中的商品无法体现折扣后的金额
- `销售流水记录` 交易已扣除折扣的金额, 展开后 商品无法显示折扣后的金额
- `销售商品汇总表` 中的商品无法显示折扣后的金额
- `销售日报表`的问题应该在 https://github.com/extensivepro/expropos/commit/5b5e07a3db7bb6d5fe15b2257b54303d13be0bc7 中解决了

@guanbo @chenshun
