### ISSUE TITLE
销售过程中的价格更改问题

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#190]
销售过程中，商品的单价可以修改，一旦改过一个商品的单价，再增加同样的商品的时候，其商品的单价自动更新了，个人觉得此处需要修改，否则怎么处理第二件半价的问题呢？

**Comment by guanbo** [comment]
第二件半价这个目前暂不考虑，这个策略太复杂了。可以第二单的形式来实现，只要留给客户足够的操作空间就可以了。
