### ISSUE TITLE
收银界面，销售结算时，点击例如“折扣金额”、“折扣比率”的切换时希望可以重置掉之前的输入。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#192]
在销售结算时，从`折扣金额`切换到`折扣比率`，或是切换到`现金付款`、`会员储值`，之前的输入都会保留，因考虑到切换之后大部分之前的输入都是错误的，所以建议在切换之后重置掉之前的输入，方便用户操作。

**Comment by guanbo** [comment]
考虑如下场景：
- 应付100，会员储值还剩20，全部用掉，其余现金。
- 全场8折，慢300再减20。

**Comment by chenshun** [comment]
我说的是录入框中的输入会保留，就是还没有点击`确认`的输入。
例如：一件商品打8折，我在结算时输入`4000`，发现忘记打折了，这时我还没有点确认，所以会再去点击到`折扣比率`，这时候的`4000`还存在，我是希望在切换的时候重置掉录入框里的输入。

**Comment by puttin** [comment]
@guanbo 这个现在怎么说? 如果按 @chenshun 所说的做, 就指派给我好了
