### ISSUE TITLE
从管理界面进入收银界面的接口隐藏的相对较深。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#193]
业主身份，从管理界面进入收银界面这个重要的功能目前隐藏的相对较深。肖总和coder曾经在使用时都是通过不厌其烦的登出再登陆的方式进入收银界面。测试初期，我也和他们一样。
建议将这个重要的功能按钮调整到一个醒目的位置,例如界面左上角或其他。

**Comment by guanbo** [comment]
同意。
你先出个低保真原型，我们讨论以后再请宗超在高保真上看下。

**Comment by chenshun** [comment]
把进入收银界面的接口调整到了左上角位置，[这是原型](https://projects.invisionapp.com/d/main#/console/292578/6211684/preview)。
