### ISSUE TITLE
WebPOS首页

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#199]
商店的用户（雇员）可以：
- 登录到系统中
- 登陆后可以登出
- 修改自己的密码

**Comment by haoxins** [comment]
- webPOS和passpro是什么关系，在issue中没看到webpos具有pos机功能，基础的会员管理与passpro是一样的。
- 如果把webpos和passpro分别做成独立的single page app，那么有些功能就重复了，比如：会员管理
- 或者，按照功能划分前端模块。pos，会员，活动/营销，数据统计/分析，当用户在webpos中点击会员管理，数据查询时，直接链接到：会员、数据统计/分析；而不是在webpos中再弄一个会员管理、数据统计

**Comment by guanbo** [comment]
> webPOS和passpro是什么关系，在issue中没看到webpos具有pos机功能，基础的会员管理与passpro是一样的。
> 如果把webpos和passpro分别做成独立的single page app，那么有些功能就重复了，比如：会员管理
> 或者，按照功能划分前端模块。pos，会员，活动/营销，数据统计/分析，当用户在webpos中点击会员管理，数据查询时，直接链接到：会员、数据统计/分析；而不是在webpos中再弄一个会员管理、数据统计
- WebPOS是面向门店雇员使用的，他的信息是受限制的。WebPOS的交易等其他功能会在后续的milestone中实现。你可以看下[wiki中的功能清单](https://github.com/extensivepro/expro-future/wiki/PassPro-Function-List)
- PassPro是面向商户管理员或业主使用，他可以完整的知道全部商户信息。
- 上面2个在功能名称上可能有相同，实现的效果完全不同，因为所在的视角不一样。例如统计销量，一个是面向经营分析的，一个只需用知道自己的分成和相关的情况。总体来说，PassPro要复杂，但主要是面向管理和制定策略，而WebPOS更多是面向实际业务操作，例如交易，其核心是服务上门用户。

我考虑问题的时候要更多的站在使用者角度，而不是开发者角度。
