### ISSUE TITLE
收银界面，充值时多次点击“现金付款”出现闪退。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#20]
进入收银界面——点击`充值`——输入相关会员——点击`确认`——点击`走入顾客`——输入充值金额——点击`确认`——点击`结算`——重复多次点击`现金付款`——程序退出

**Comment by guanbo** [comment]
已经在https://github.com/extensivepro/expropos/commit/ecafbe086d05325af7b787b939e35d77b0ceb535 修复
