### ISSUE TITLE
同步相关问题讨论

### ISSUE THREAD

**Issue by puttin** [extensivepro/expro-future-test#206]
# 常见使用场景
1. 单机完全离线使用
2. 单机同步使用
3. 多机同步使用
## 使用场景特征
1. `单机离线使用`和`单机同步使用`都无需考虑新建商品等同步的问题, 因为只有一台设备; `多机同步使用`需要考虑新建商品等尽快同步的问题
2. `多机同步使用`还需要考虑管理页面及销售页面数据统计时的准确性问题, 也和同步机制有关
# 同步机制
## 同步方式可选项
1. 每隔XX时间自动同步
2. 完全手动同步
3. 混合?(可设置新建商品等及常规同步方式:手动 自动)
## 每隔XX时间自动同步

比较傻瓜, 用户无需也感受不到同步的概念
每隔XX时间应当可以由用户设定
### 存在的问题
1. 如何处理新建商品, 库存, 会员等信息时多终端尽快同步的问题
### 问题的解决方法
- 针对所有操作设定较短的同步间隔时间, 例如30秒
- 针对新建, 修改及删除商品, 库存, 会员, 雇员四种行为可以单独设定同步间隔(轮询)时间, 而其他新增交易, 充值等使用默认的同步间隔时间
## 完全手动同步

用户需要了解同步的概念
### 存在的问题
1. 对用户使用存在一些障碍, 用户需要学习了解同步以后才能完成正常使用同步功能
2. 用户在新建商品等行为后不一定有意识去手动同步
### 问题的解决方法
- 给予相应的同步帮助, 引导用户完成首次同步, 并提供帮助页面
- 新建商品等行为后闪烁手动同步按钮(可考虑其他方式)
# 同步流程
1. 用户需首先在登陆页面上传商店
2. 用户进行相应同步设置, 提供一套默认设置
3. 根据实际设置, 自动或手动同步
# 

有什么想法建议留言讨论
@guanbo @chenshun

**Comment by guanbo** [comment]
## 同步的数据有两种类型
- 基础数据
  - 商户
  - 店铺
  - 雇员
  - 会员
  - 商品
- 交易数据
  - 购买
  - 退货
  - 充值
  - 积分

两种数据部是绝对，只要基础数据是变动相对固定的数据，同时也是作为交易数据的基础元素存在的。

## 同步方式和策略
- 首先必须要支持手动同步，在收银和管理界面都要提供明显的同步入口。
- 在应用在前台的时候，并且外接电源和网络在线的情况下后台进行轮询。
- 同步的方式也因数据类型的而不同，基础和交易数据分开同步。
- 原则上优先同步基础数据，特别是在自动同步的情况下。
