### ISSUE TITLE
系统用户中用户头像哪里来的？

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#215]
不清楚系统用户中用户头像的来源，也没看到提供修改的地方？

**Comment by guanbo** [comment]
目前暂用的临时图片，固定地址。

**Comment by guanbo** [comment]
- 在User中加入头像属性，保存头像的链接地址。
- 提供上传头像功能，并且保存头像到OSS上。
  - 提供裁剪头像功能。
- 有头像的账号在前端显示OSS上保存的头像，没有用default头像。
