### ISSUE TITLE
POS对账时，直接点击确认会出现一个默认的时间。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#218]
POS收银界面，在对账过程中，不做任何输入点击`确认`会出现一个默认时间。在实际操作时，如果用户输入一个想要的时间，不注意点击了两次`确认`，则后面默认的时间会覆盖掉用户之前输入的时间，造成麻烦，建议调整。

**Comment by guanbo** [comment]
在输入过一次以后，默认时间为空，为空的时候，输入无效。

**Comment by puttin** [comment]
@guanbo 我之前打算设成默认时间就是当前时间

**Comment by guanbo** [comment]
> 不注意点击了两次确认，则后面默认的时间会覆盖掉用户之前输入的时间，造成麻烦，建议调整。

注意是后面会覆盖前面

**Comment by puttin** [comment]
@guanbo 我说那个201306180000改成当前时间或者前一天时间或者允许设置
按两次好解决
