### ISSUE TITLE
POS管理界面，会员详情中，储值记录把储值消费也记录进去了

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#219]
### 步骤
1. 进入收银界面，使用会员储值完成一次销售商品
2. 切换到管理界面，点击`会员`，点击`>`进入会员详情
### 结果

可以看到下方的`储值金额`把刚才消费的也记录进去了
### 期望

`储值金额`中只显示会员的充值记录

**Comment by puttin** [comment]
原来是设计上就是这么做的...

但之后会区分出来充值是有`+`
储值消费会有`-`
