### ISSUE TITLE
销售的商品库存信息添加之后无法修改

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#22]
一件商品，在`商品详情`中可以添加不同型号的库存，增加的库存无法修改。建议加入对`库存`的编辑功能，这样可以修改错误的操作

**Comment by chenshun** [comment]
还要把`库存`右侧的`+`显示出来。

**Comment by guanbo** [comment]
1. 由于交易、统计等功能都需要基于SKU。如果将库存删掉有可能会造成数据错误。所以目前没有删除库存功能。
2. 对于误操作的问题，我在新增库存的时候可以考虑弹框确认，减小误操作概率。

> 还要把库存右侧的+显示出来。

@puttin 请关注。

**Comment by puttin** [comment]
该Issue与 https://github.com/extensivepro/expropos/issues/42 相关
