### ISSUE TITLE
POS收银界面，退货过程中可能出现的问题。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#220]
1. 一笔交易中同时含有`现金付款`和`储值付款`，在退货时，如果分两次或以上次数退货，则退货后的`退款金额≠支付现金`，`退款储值≠支付储值`，因为每次退货都是全数退还`储值金额`，如果分两次退，那么`退款储值`就会乘以`2`。
2. 一笔交易中如果有折扣比例，那么退货时设定的退货价格也会按照该折扣数来算并且不可调整，很不合理。例如一件商品7折出售，退货时不是全额退款，只能退给顾客部分金额，如`2000`，则输入到账单中就会调整为`1400`，实际上退货并不需要按照这个折扣来计算。

**Comment by chenshun** [comment]
针对问题1，建议调整为要么全是现金付款，要么全是会员储值付款。三个理由：
- 实际生活中可以同时使用会员储值和现金支付的似乎很少，一般商家在会员储值不够时都会鼓励会员继续充值，要么就使用现金。商家都不希望自己的会员把账户里的钱刚好花完。
- 一般会员卡都享有折扣，如果部分使用储值消费，部分使用现金，那么会员的折扣还能不能享受到？
- 可以避免诸如退货这类问题的发生。

**Comment by guanbo** [comment]
> 针对问题1，建议调整为要么全是现金付款，要么全是会员储值付款。三个理由：
> 
> 实际生活中可以同时使用会员储值和现金支付的似乎很少，一般商家在会员储值不够时都会鼓励会员继续充值，要么就使用现金。商家都不希望自己的会员把账户里的钱刚好花完。
> 一般会员卡都享有折扣，如果部分使用储值消费，部分使用现金，那么会员的折扣还能不能享受到？
> 可以避免诸如退货这类问题的发生。
- 调整支付方式在一次交易中只采用一个方式。
- 退货是不可避免的。

> 一笔交易中如果有折扣比例，那么退货时设定的退货价格也会按照该折扣数来算并且不可调整，很不合理。例如一件商品7折出售，退货时不是全额退款，只能退给顾客部分金额，如2000，则输入到账单中就会调整为1400，实际上退货并不需要按照这个折扣来计算。

如果退货的时候不按折扣来计算，顾客不是会拿到比付的更多的钱？这可以作为一个基准，可以手动调节退款金额。

**Comment by chenshun** [comment]
> 退货是不可避免的。  

我的意思是避免退货时出现遇到退款与支付不一致的情况。

> 如果退货的时候不按折扣来计算，顾客不是会拿到比付的更多的钱？这可以作为一个基准，可以手动调节退款金额。  

可不可以在退货时，退货账单中的`总计金额=销售时的支付金额`，即经过计算去除之前打折的部分，生成一个新的`退货账单`，而不是在原来`销售账单`的基础上生成出来。

**Comment by guanbo** [comment]
> > 退货是不可避免的。
> > 我的意思是避免退货时出现遇到退款与支付不一致的情况。

退款的情况可能很复杂，例如全额，全额+赔偿，少于全额等情况，我们只有给操作的人一个调整的参考。

> 可不可以在退货时，退货账单中的总计金额=销售时的支付金额，即经过计算去除之前打折的部分，生成一个新的退货账单，而不是在原来销售账单的基础上生成出来。

现在退单就是一个相对于销售独立的清单。之所以要原始收据，是参考现实中很多退货必须有销售凭据的场景。

**Comment by puttin** [comment]
第一个问题终于找到原因了...非常坑爹
我再看看第二个
