### ISSUE TITLE
门店员工编辑中门店数据哪里来？

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#221]
![snap2](https://f.cloud.github.com/assets/2062648/1048085/e0311d5e-1082-11e3-9eaf-31a5ae80fe74.jpg)
如上图：门店数据哪里啦的？此事门店没有一号店的数据

**Comment by guanbo** [comment]
1号店是开局数据，肯定有。如果没有，应该是显示上有问题。
