### ISSUE TITLE
POS 同时存在正式 与 体验 数据库的设想

### ISSUE THREAD

**Issue by puttin** [extensivepro/expro-future-test#228]
使用两套数据库:
- 体验
- 正式

原因: 不会遗留垃圾
缺点:逻辑上和实现上稍显复杂

相关设想:
1. 登录界面 右上方可以选择体验 正式
2. 选择正式使用后若不存在正式数据库引导用户建立完整商户商店等信息

存在的问题:
体验数据导出? 如果现有用户没有正式使用 那不导出也不会成为问题

**Comment by guanbo** [comment]
从反馈看，用户还是重视删除功能。所以在有删除功能下的体验库就缺乏必要性了。

**Comment by puttin** [comment]
@guanbo 删除本来就是要做的 弄体验库的唯一原因就是初始数据即使标记删除了 有的用户可能还是难受
