### ISSUE TITLE
收银界面，关于退货的时候选择要退的商品

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#23]
在收银界面的`流水`中，点击选取要退的商品时，如果点击中间的`单价`或`数量`位置，会进入修改的形式，实际上并不能修改，这样会影响到选中商品，体验不好。建议在流水中取消掉这个，这样无论点击哪里都能选中该商品进行退货。

**Comment by chenshun** [comment]
另外考虑到如果购买了一批商品，其中几个有质量问题要退掉，那么退货中的`数量`是应该可以修改的，但是实际操作`数量`修改不了，这应该是个BUG

**Comment by guanbo** [comment]
> 另外考虑到如果购买了一批商品，其中几个有质量问题要退掉，那么退货中的数量是应该可以修改的，但是实际操作数量修改不了，这应该是个BUG

是可以修改的，在选择完以后，结算之前。可以编辑退货数量和价格。

**Comment by guanbo** [comment]
> 在收银界面的流水中，点击选取要退的商品时，如果点击中间的单价或数量位置，会进入修改的形式，实际上并不能修改，这样会影响到选中商品，体验不好。建议在流水中取消掉这个，这样无论点击哪里都能选中该商品进行退货。

将调整为选择退货项目的时候不可编辑数量和价格。
