### ISSUE TITLE
PassProCRM--“新增门店员工”有两个“编号”的输入框

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#231]
### 步骤
1. 登入系统，点击`门店管理`
2. 点击`门店员工`，点击列表右上角`+`
### 结果

> ![image](https://f.cloud.github.com/assets/3068259/1071665/ef026336-147b-11e3-9317-5fc1d3b4b907.png)
### 期望

去掉一个`编号`

**Comment by guanbo** [comment]
@chenshun 请标记commit后关闭

**Comment by chenshun** [comment]
https://github.com/extensivepro/expro-future/commit/fc57b111c8b8ad5b8a904646520ab9d697db00a6
