### ISSUE TITLE
POS系统，退货之后的若干问题。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#235]
#### 销售出去的商品执行过退货之后：
- `销售日报表`没有变化，与退货之前一样，那么成交数量与消费情况就与实际情况不符。
- `销售商品汇总表`仍有该退货商品的销售情况，实际上该商品并未销售出去。
- `库存汇总表`没有变化，`销售数量`与`结存数量`仍是未退货之前的。

**Comment by puttin** [comment]
`销售日报表` 的 统计的是 `交易` 的数量, 所以非 `交易` 的行为, 比如 `退货` 就不会被记录下来 从而也体现不出来
