### ISSUE TITLE
POS界面实现手动积分

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#238]
## 前置条件
- 登陆到收银系统
- 无需进行销售的情况
## 过程
- 直接选择会员
- 输入数字进行积分
## 期望
- 输入的数字可以累积到会员的累计积分上

请 @chenshun 完成原型设计后，由王延之实现。

**Comment by chenshun** [comment]
POS收银界面加入积分功能，[这是原型](https://projects.invisionapp.com/d/main#/console/292578/9312138/preview)。

**Comment by chenshun** [comment]
本次修改主要涉及三个地方：
- 调整了`用户切换`到左上角，右上角方框变更为提示操作步骤。提示的字体需要放小，不然只能显示几个字。
- 变更了输入会员编码的接口，不再是左侧`选择会员`按键，而是在`会员`和`销售`模块的一开始直接输入会员编码。原来的`选择会员`将只用来显示顾客身份，不可点击。
- 增加`会员`模块，原先的`充值`变更为`会员`子模块。
