### ISSUE TITLE
退货时的交易号会变化

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#24]
### 步骤

1.点击`流水`
2.输入一个交易号，点击`确认`
3.选中要退的商品，点击`退货`
### 结果

可以看到左上角交易号变成了另一个交易号
### 期望

交易号不变

**Comment by chenshun** [comment]
另外，再次点击退货退货完成，高保真中显示出`退货账单`，而实际操作中没有变为`退货账单`，显示的仍然是交易账单，是做出了调整还是BUG？

**Comment by guanbo** [comment]
> 期望
> 
> 交易号不变

交易号是是退单的交易号，不是销售的交易号，肯定是不相同的。

> 另外，再次点击退货退货完成，高保真中显示出退货账单，而实际操作中没有变为退货账单，显示的仍然是交易账单，是做出了调整还是BUG？

可能是状态问题，需要调整。

**Comment by chenshun** [comment]
高保真中的退单会显示成`退单号`并且带出之前的`交易号`，感觉那样更好

**Comment by guanbo** [comment]
> 高保真中的退单会显示成退单号并且带出之前的交易号，感觉那样更好

将调整为退单号
