### ISSUE TITLE
会员充值界面无法取消

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#245]
进入会员充值界面，点击取消按钮，提示要填写充值金额字段，不能退出。

**Comment by xiaoyuxiong** [comment]
如果充值金额不填，为空的话，点击创建，无提示，无反应。

**Comment by guanbo** [comment]
PassPro CRM
- 对于由主菜单进入充值界面的，将隐藏取消按钮。
- 由其他地方进入到充值界面，取消后返回进入界面。

**Comment by guanbo** [comment]
Fixed:  @ cae1ee0dfc2fd7f7c6a45fa6e57578721e451eba
