### ISSUE TITLE
充值问题汇总

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#246]
1.充值记录管理员可否随便删除；
2.现在在可以删除充值记录情况下的问题，如果一个会员经过上次充值50元后，余额为100元，如果删除充值50元的记录后，该会员的余额变成了150元；
3.尚有储值余额的会员管理能否随便删除；
4.储值有效期是否考虑；

**Comment by guanbo** [comment]
> 1.充值记录管理员可否随便删除；
- [x] 调整为不可以删除

> 2.现在在可以删除充值记录情况下的问题，如果一个会员经过上次充值50元后，余额为100元，如果删除充值50元的记录后，该会员的余额变成了150元；
- [x] 错误充值记录的情况，新增一条对冲记录

> 3.尚有储值余额的会员管理能否随便删除；
- [x] 调整为不可以删除。

> 4.储值有效期是否考虑；
- [x] 暂不考虑有效期，等待客户需求。

**Comment by guanbo** [comment]
在充值界面加入冲销按钮

**Comment by MengWei** [comment]
冲销按钮不可点击，请修复。

**Comment by guanbo** [comment]
需要先输入冲销金额

**Comment by chenshun** [comment]
> 1.充值记录管理员可否随便删除；
> - [x] 调整为不可以删除

点击查看进入详情界面仍然可以删除。点击`删除`页面不会跳转，但是该记录就被删了。

**Comment by chenshun** [comment]
> 3.尚有储值余额的会员管理能否随便删除；
> - [x] 调整为不可以删除。

仍然可以删除。
