### ISSUE TITLE
收银界面，充值的时候如果点击取消，则后续操作无法完成

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#25]
### 步骤

1.点击`充值`
2.输入会员编号点击`确认`
3.输入充值金额点击`确认`
4.点击`取消`
5.重新输入充值金额点击`确认`
### 结果

右侧的交易账单中没有显示充值金额等一系列变化
### 期望

右侧交易账单显示正常

**Comment by guanbo** [comment]
Fixed https://github.com/extensivepro/expropos/commit/b408bfd451116f47c7cdf39be0dbfce617003717
