### ISSUE TITLE
新建门店基础数据建议加入地理坐标

### ISSUE THREAD

**Issue by MengWei** [extensivepro/expro-future-test#250]
新建门店缺少地理坐标位置设置，并且门店状态按钮点击后很难看出当前所选的状态。

**Comment by guanbo** [comment]
- 保存GeoJSON到门店信息，参考[交互协议](https://github.com/extensivepro/expro-future-test/blob/master/webservice/interface/shops.md)
- 在门店详情中地图展示，调用[高德地图](http://api.amap.com/ios/index)实现。我们申请的key：4fc11282e44bd7d40a06eff9f0ee7ffd
