### ISSUE TITLE
响应式设计有布局问题

### ISSUE THREAD

**Issue by MengWei** [extensivepro/expro-future-test#252]
页面使用了响应式设计的方式，但是在页面改变大小是没有能很好的适配屏幕。
例如缩小屏幕宽度，菜单栏和页面内容区域会重叠覆盖，使得系统无法使用。

**Comment by guanbo** [comment]
- 上图，有图有真相。
- 如果缩放到太小得屏幕没有意义，客户只要放到全屏即可。没有必要在这上面化太多时间。
