### ISSUE TITLE
希望能增加门店财务日报功能

### ISSUE THREAD

**Issue by MengWei** [extensivepro/expro-future-test#253]
可以使用人工输入的方式，每日一次的录入对应门店的：收入，支出，客流，VIP交易数等信息；
可以进行日报展现；
可以进行月报统计分析（曲线图等）；
可以提供数据API供客户端调用；

**Comment by guanbo** [comment]
> 可以使用人工输入的方式，每日一次的录入对应门店的：收入，支出，客流，VIP交易数等信息；

分解到 #255 

> 可以进行日报展现；
> 可以进行月报统计分析（曲线图等）；

分解到 #240 dashboard中体现

> 可以提供数据API供客户端调用；

单独分解一个issue，说明需求的数据情况，例如：销售额，会员消费额度等
