### ISSUE TITLE
定制微信公众号客户端菜单

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#259]
## 前置条件
- 用户登录到管理后台
- 微信接入服务器和微信对接正常
## 操作
- 在预制的客户端菜单中编辑菜单和子菜单，管理各菜单反馈的消息
- 将编辑的结果保存到本地
- 保存菜单提交到微信服务
## 预期
- 编制的菜单可以在界面上预览
- 微信客户端可以看到调整后的菜单

**Comment by haoxins** [comment]
目前没有微信后端管理界面，是否需要自己做一个后端管理界面？
1.  由于腾讯自己的界面基本功能都有了，我们做（给第三方用），明显多余
2.  如果是crm业务相关的，就应该作为crm的一个功能页面，并且侧重点在于与会员关于业务的交流，而不是消息。

正常的场景是：
业主自己有个服务号，然后出入ak，sk。

业主设置菜单选项，可以勾选我们提供的服务（查询会员积分等。。。。）
我们可以处理回复

### 由于考虑到小商户，所以我们起一个服务，服务n个服务号。

通过传过来的message里的key的设置辨别商家。。。。

提供微信服务号服务应该是我们的一个功能， **亮点** 。不应该向原先讲的，让客户基于我们的代码部署。

**Comment by guanbo** [comment]
- 泛卡汇里面的微信是组成部分，如你所想。
- 作为组件的目的是可以被复用，可以进行简单的配置完成服务号
- 需要有自助服务包括配置微信账号、定制功能等
- 我们的系统启用后用户是不能使用微信自带的菜单定制
