### ISSUE TITLE
定制预制回复消息

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#260]
## 前置条件
- 登录到管理后台
## 操作
- 通过消息编辑界面预制消息，包括如下类型
  - 文本
  - 图片
  - 语音
  - 视频
  - 图文
  - 业务生成，有业务代码生成并在系统中注册形成的消息
- 保存编辑的消息到本地
## 预期
- 可以在本地预览到预制的消息
- 其他功能可以选择对应的消息回复

**Comment by haoxins** [comment]
https://github.com/extensivepro/expro-future-test/issues/259
个人觉得可以考虑把服务号的消息回复，菜单。。。。。。作为我们的一个服务。

我们起一个服务，为n个商户的服务号服务。

**Comment by guanbo** [comment]
与本issue无关
