### ISSUE TITLE
POS收银界面，销售完成后的打印界面显示的不是销售账单

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#268]
### 步骤
1. 进入POS收银界面，完成一次销售
### 结果

销售完成后的打印界面显示的是会员信息
### 期望

希望可以停留在结算账单界面

**Comment by chenshun** [comment]
同时包括会员的`充值金额`与`充值积分`两个部分。

**Comment by puttin** [comment]
`销售`, `充值` 结束后应当可以快速进入下一笔`销售`, `充值`
而下一笔 是从`选择会员`开始
如果左侧详情显示的仍然是上一笔的详情 但右侧控制版处显示的是对会员的相关操作 和 相关提示

会不会更加奇怪一些

@chenshun 为何希望可以停留在结算账单界面?

**Comment by chenshun** [comment]
- 一方面考虑到账单的打印，如果结算完成后显示的不是账单，那么打印出来的是什么内容？
- 另一方面结算完成后，看不到结算账单，作为收银员心里会不会没有底，因为没有确认刚才的操作得到了什么结果。

**Comment by puttin** [comment]
> 另一方面结算完成后，看不到结算账单，作为收银员心里会不会没有底，因为没有确认刚才的操作得到了什么结果。

点结算前就应该确认清楚

> 一方面考虑到账单的打印，如果结算完成后显示的不是账单，那么打印出来的是什么内容？

但是如果只是为了打印, 而左侧详情显示与右侧控制处的提示不符合 未免有些得不偿失

如果真的考虑到打印确认前要显示的话 我现在的想法是打印选项还在显示的时候 显示对应的详情

打印选项消失后显示选择会员界面

@chenshun  @guanbo

**Comment by puttin** [comment]
调整为结算后显示上一笔

输入新的会员号后显示新的会员详情
