### ISSUE TITLE
POS收银系统，会员储值与积分充值过程，点击取消返回的不是上一级操作。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#270]
### 步骤
1. 进入收银系统，点击`会员`
2. 输入会员编码，点击`确认`
3. 选择`充值`，输入`200`点击`确认`
4. 点击`取消`
### 结果

返回到`会员`初始界面
### 期望

返回`充值`与`积分`的选择界面，这样就可以不用再次输入会员编码，重新进行充值

**Comment by puttin** [comment]
之前主要是考虑这里的取消更多的是象征取消这笔`充值`行为
而重新输入新的会员编号也不麻烦

我稍后先提交个返回上一级操作的版本把
