### ISSUE TITLE
泛商汇POS为iPad提供优化图标

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#275]
按Apple官方的策略，iPad在iOS7以后最好提供一下尺寸的图片，以达到优化效果
App Kind （icon）
- iPad Non-Retain 72x72
- iPad Retain 152x152

Spotlight Kind
- iPad Non-Retain （iOS <= 6.1) 50x50
- iPad Retain（iOS <= 6.1) 100x100
- iPad Non-Retain 40x40
- iPad Retain 80x80

Setting Kind
- iPad Non-Retain 29x29
- iPad Retain 58x58

需要注意：
- 请联系美工出图，
- 需要升级到XCode5

**Comment by puttin** [comment]
几个 retina
还有 `iPad Non-Retain 72x72` 应为 `iPad Non-Retain 76x76`
72pt 的已经有了
