### ISSUE TITLE
泛商汇iOS7适配

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#276]
在 iOS7环境管理界面布局错误
![ios 2013-9-21 1 51 25](https://f.cloud.github.com/assets/712444/1185107/f0c3ec12-2281-11e3-8fa2-d2971446b21b.png)
收银界面
![ios 2013-9-21 1 52 45](https://f.cloud.github.com/assets/712444/1185111/1c3da48c-2282-11e3-9d94-977da0a4b50d.png)

**Comment by puttin** [comment]
在重新设计前, 除了上述明显的, 还有:
- [x] 状态栏
- [x] Group 表格 只能勉强能用
- [x] picker view 只能勉强能用
