### ISSUE TITLE
POS收银系统，商品退货之后，原本的交易账单发生变化。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#285]
### 步骤
1. 进入POS收银系统，点击`流水`
2. 输入`交易流水号`，点击`确认`
3. 选择账单中商品，点击`退货`
4. 再次点击`退货`完成退货
5. 重新输入刚才的`交易流水号`，查看交易账单
### 结果

可以看到账单中的`小计`产生变化
### 期望

交易账单始终不会发生变化

**Comment by puttin** [comment]
这个问题修复后测试时需要注意#235 中提到的:

`销售商品汇总表`仍有该退货商品的销售情况，实际上该商品并未销售出去。
`库存汇总表`没有变化，销售数量与结存数量仍是未退货之前的。
