### ISSUE TITLE
POS收银系统，按键在点击之后的滚动过程中可点击，快速点击其他按键造成出现错误的操作界面，有时程序也会闪退

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#286]
### 步骤
1. 进入POS收银系统，点击`销售`
2. 选择销售对象，例如`普通`
3. 输入商品编码，选择销售商品
4. 点击`结算`，按键开始滚动，快速点击旁边`取消`，来回多次点击
### 结果

出现双`取消`和`结算`按键，也有可能程序闪退
### 期望

避免上述出现的错误

**Comment by puttin** [comment]
模拟器中 进入销售页面 -> Cmd+T -> 然后先点`取消`再点`结算`
