### ISSUE TITLE
POS管理系统，商品和库存模块需要做出调整。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#287]
目前的POS管理系统，商品与库存的关系：用户需先进货，然后生成该商品，新增商品接口唯一。
而在实际生活中，用户店里已经有很多商品正在出售，这些商品不需要经过进货这一环节，但是需要把数据统计到POS中，所以现在的设计不能满足部分用户的需求。需要做出调整。

**Comment by puttin** [comment]
中午@guanbo 提到一个问题:
1. 用户还是不知道要到`库存汇总表` 处 新增`库存` 或者`商品`后 进行销售  
   可以考虑把相关页面的`库存`都统一改成 `进货` 便于理解

我认为:

> 实际生活中，用户店里已经有很多商品正在出售，这些商品不需要经过进货这一环节，但是需要把数据统计到POS中

这种情况, 就进一批当前数量的货物(`库存`)就好了

**Comment by puttin** [comment]
@guanbo 不能光指派给我啊 我都不知道按怎样的做

**Comment by guanbo** [comment]
@chenshun 请按昨天讨论的意见出原型。

**Comment by chenshun** [comment]
@puttin POS管理系统--[首页原型](https://projects.invisionapp.com/d/main#/console/292578/9703208/preview)

**Comment by puttin** [comment]
- [x] 首页
- [x] `库存流水`调整为 `进货`
- [x] `增加库存` 由`库存汇总` 移至 `进货`
