### ISSUE TITLE
新开商户的必填信息没有限制

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#29]
### 步骤

1.点击左下角用户头像，进入设置界面
2.点击当前商户名，进入商户列表
3.点击右上角`+`，进入新开商户界面
4.不输入任何资料，点击存储
### 结果

添加成功，一个空白的商户在商户列表中出现
### 期望

新开商户中要输入的信息均为必填，不能为空，并且对电话号码和电子邮件的格式要能验证

**Comment by puttin** [comment]
该Issue与 https://github.com/extensivepro/expropos/issues/42 相关
