### ISSUE TITLE
商店界面，部分表单右上角点击搜索按钮再点击取消没有反应，并且不能筛选出相应结果。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#3]
以下表单搜索时点击取消无反应，并且不能筛选出结果：`销售商品汇总表`、`付款流水记录`、`库存流水记录`、`库存汇总表`、`商品`、`会员`、`雇员`

**Comment by puttin** [comment]
在 https://github.com/extensivepro/expropos/commit/0aad69f64491a0b9c469113a4144ab08727c34b2 中修复了
