### ISSUE TITLE
关于 泛盈科技微信客服 的菜单项设置

### ISSUE THREAD

**Issue by haoxins** [extensivepro/expro-future-test#300]
![08d89b84-4d86-4b45-80b9-b5356b5f2386](https://f.cloud.github.com/assets/2569835/1232381/2cd1f9c8-28af-11e3-9fb0-917f3a0ed63e.png)

一级按钮的个数必须为：2~3 个
二级选项的个数必须为：2~5 个

所以，可设置的选项为 4~15 个

初步设想：

<table>
<thead>
  <tr>
    <th>泛商会</th>
    <th>软件定制</th>
    <th>关于我们</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>POS</td>
    <td>app开发</td>
    <td>成功案例</td>
  </tr>
  <tr>
    <td>CRM</td>
    <td>服务开发</td>
    <td>合作伙伴</td>
  </tr>
</tbody>
</table>

关于按钮，有两种。一是：click类型，我们设置回复消息。还有就是链接。

**Comment by haoxins** [comment]
请各位集思广益。
@guanbo 
@MengWei 
@chenshun 
@ngot 
@puttin 

除了菜单外，对应的文案也急需！

help! help! help!

**Comment by guanbo** [comment]
- 我们的这个号是产品客户服务，重点是帮客户解决产品售后服务和售前咨询的问题。
- 可以在最后的菜单中放入软件定制和公司介绍。
- 上述都以页面链接的形式展现出来。

## 菜单
- `泛商汇` 以图文消息的方式在展现，包括下面的链接入口（非子菜单）
  - 简介
  - 常见问题
- `泛卡汇`
  - 简介
  - 常见问题
  - 会员信息 反馈作为泛卡汇会员的信息情况， #258 。
- `我们` 包含下面子菜单
  - `关于泛盈` 在菜单底部，展示公司简介的链接
  - `软件定制` 展示我们的成功案例的链接，在链接中包含我们定制的方法。

## 文案
- `产品简介`  @guanbo整理 #302 #302 
- `常见问题` @chenshun 请整理出初稿交由 @xiaoyuxiong 安排行政方面对产品不熟悉的人试用产品后评审。 #303 #304 
- `关于泛盈`和`软件定制`部分先采用公司网站上内容。

## 移动端响应

@coderhaoxin 所有链接需要针对移动端做成响应式设计

**Comment by haoxins** [comment]
现有菜单里没有功能选项：比如，查询积分。。。。。。。。。。。。

**Comment by guanbo** [comment]
#258 中已经包含了查积分。请看issue仔细点。
