### ISSUE TITLE
POS管理界面，“设置”中的“新商户”有歧义，需要调整。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#306]
之前`设置`中的`新商户`可以用来设置商户名称以及添加`新商店`，但是现在只是用来编辑商店详情，因此建议改为`商店设置`，这样可以引导用户将自己的商店信息录入其中。

**Comment by puttin** [comment]
实际上 这个 "新商户" 不是传统意义上的新的商户的概念
而是初始数据中 商户"新商户商贸有限公司" 的缩写 "新商户"
是比较容易有歧义
cc @guanbo 给初始数据改个名字?

**Comment by guanbo** [comment]
同意 @puttin

**Comment by chenshun** [comment]
@puttin “朝阳商贸”字段需替换为“当前商店”。
