### ISSUE TITLE
POS首页新增加的报表反映的数据不够全面

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#318]
- 没有反映出会员总数、商品总数、总销售额、总收入、总支出；
- 今日和昨日的数据对比表中，没有反映出会员的充值情况。

**Comment by guanbo** [comment]
> 没有反映出会员总数、商品总数、总销售额、总收入、总支出；

@chenshun 修订原型首页体现存量信息。

> 今日和昨日的数据对比表中，没有反映出会员的充值情况。

这块先不体现吧，因为考虑充值情况要少于交易的情况。业务应该是更关注沉淀的预付费。后期如果有反馈我们再调整。

**Comment by chenshun** [comment]
> 修订原型首页体现存量信息。  

存量信息的范围是商户还是商店？

**Comment by guanbo** [comment]
商店范围的存量，增量信息也是。

**Comment by chenshun** [comment]
[首页最终原型](https://projects.invisionapp.com/share/U5G9MLAY#/screens/9703208?maintainScrollPosition)
存量数据只显示了四个，待补充。

**Comment by guanbo** [comment]
@chenshun 可以先按[高保真原型](https://projects.invisionapp.com/share/U5G9MLAY#/screens/10188404?maintainScrollPosition=false)来操作，总收入和总支出等库存完善成本支出后再完善。
