### ISSUE TITLE
OpenUDID应当被废弃

### ISSUE THREAD

**Issue by puttin** [extensivepro/expro-future-test#319]
[OpenUDID](https://github.com/ylechelle/OpenUDID) ReadMe 中提到了如下这篇文章:

[UDID is dead, OpenUDID is deprecated, long live advertisingIdentifier!](http://blog.appsfire.com/udid-is-dead-openudid-is-deprecated-long-live-advertisingidentifier/)

**Comment by guanbo** [comment]
这个可以建立expropos的项目中。

**Comment by puttin** [comment]
习惯了…给忘了 需要在 expropos 里重建吗?

这个问题就用这个好了

以后会注意
