### ISSUE TITLE
面向扫描枪重构进货界面

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#324]
- 目前进货界面设计时候没有考虑扫描枪使用的情况，进货的体验不好。
- 在新增商品的时候需要考虑将必要输入集中在一起，这样方便用户在键盘上点击“下一步”来切换。
- 对于进货登记过的老商品请要求做到只要扫入后，带出产品信息，只要输入数字和售价（可选）即可
- 请重新考虑设计交互界面。

**Comment by chenshun** [comment]
重新调整商品信息的布局，将`商品编码`移至最前。扫描后，带出商品编码，输入光标停留在`商品名称`位置。
[进货低保真原型](https://projects.invisionapp.com/d/main#/console/292578/10828603/preview)

**Comment by puttin** [comment]
现在这个算解决没有?
