### ISSUE TITLE
POS收银系统，库存查询时建议在没有任何输入的情况下，可以查询全部商品

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#326]
### 步骤
1. 进入POS收银系统，点击`库存`
2. 直接点击右下角`确认`
### 结果

无反应
### 期望

显示出所有商品库存信息，方便收银员查询

**Comment by puttin** [comment]
这个是先这样做么?

库存界面还需要保留么?
@chenshun @guanbo

**Comment by guanbo** [comment]
暂时不调整这块
