### ISSUE TITLE
POS在新增会员过程中存在的问题。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#327]
在进行`新增会员`的操作时：
- `会员编码`需要手动输入，建议系统带出默认编码。
- `电子邮箱`是否有必要在创建过程中显示？
- `会员类型`需要手动输入，建议系统默认带出，不同类型的会员应该是可供选择的。
- `有效期至`应该直接默认显示出来，并且可供选择。

**Comment by guanbo** [comment]
> 会员编码需要手动输入，建议系统带出默认编码。

建议编码自增体系，自动带出

> 电子邮箱是否有必要在创建过程中显示？

保留作为可选

> 会员类型需要手动输入，建议系统默认带出，不同类型的会员应该是可供选择的。

目前先自动带出显示类型为`会员`，会员类型需要新增类型的管理，建议另起一个issue。

> 有效期至应该直接默认显示出来，并且可供选择。

有效期默认到一年以后，可以选择永久有效。这块需要加入友盟统计，看选择哪种有效期的多。再根据数据调整默认有效期。

**Comment by puttin** [comment]
并不是很紧急的问题, 暂不在云存储3中解决吧

**Comment by puttin** [comment]
暂不在云存储4中解决

**Comment by puttin** [comment]
`自增`小组讨论暂不解决
