### ISSUE TITLE
POS管理系统，进货窗口中的红色边框提示问题。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#328]
### 步骤
1. 进入POS管理界面，点击`进货`
2. 选择商品或者新建商品
3. 在`数量`中做出错误的输入，例如`a`
4. 点击软键盘中的`换行`
### 结果

没有提示错误
### 期望

立刻对用户的输入做出校验，在不正确的情况下直接给出提示。

**Comment by puttin** [comment]
我的理解是跳转时直接提示而不是点击确认才提示?

**Comment by chenshun** [comment]
对。
