### ISSUE TITLE
POS管理系统，销售日报表刷新时提示的LOGO太明显，体验不好

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#337]
每次点击`销售日报表`，会有一个刷新的动作，这个动作太明显，其他列表都没有，形成强烈的落差，影响体验。
建议将刷新的LOGO变小，放到数据表中，而不是整个屏幕正中间，从而减少与其他列表在切换时产生的差别。

**Comment by guanbo** [comment]
- 对应费时操作的都需要加入Loading的提示，其他列表根据需要加。
- 提示中需要有退出机制，防止刷新过长。

**Comment by puttin** [comment]
相关 Commit https://github.com/extensivepro/expropos/commit/ece7be7376d66e1ee8c92a64376ffc2026fac428
