### ISSUE TITLE
POS收银管理员登录后翻转动画非常生硬

### ISSUE THREAD

**Issue by MengWei** [extensivepro/expro-future-test#34]
设备：iPad2 16g
翻转动画很卡，很生硬，若无法实现流畅的动画效果，不过改为左右滑动或者取消动画。

**Comment by puttin** [comment]
@guanbo 可以尝试取消`transitionWithView:duration:options:animations:completion:` 就是没有动画会比较突兀

猜测让人感觉卡顿的主要原因是默认会把SplitViewController 从Portrait转成Landscape 把动画时间延长点就能看到
