### ISSUE TITLE
POS 收银在删除商品时，删除按钮应该盖住数字

### ISSUE THREAD

**Issue by MengWei** [extensivepro/expro-future-test#349]
现在的问题是数字浮在按钮之上，请修正为按钮遮盖住数字。

**Comment by MengWei** [comment]
![qq20131114-1](https://f.cloud.github.com/assets/1725086/1539931/bb528fca-4d15-11e3-88b7-afdf50e3c8df.png)

**Comment by puttin** [comment]
已在 https://github.com/extensivepro/expropos/commit/251b25a32d7e2bd437784c9d4ecd15c238f25b1c#diff-16 解决
