### ISSUE TITLE
为何我进入POS收银界面感到无所适从？

### ISSUE THREAD

**Issue by MengWei** [extensivepro/expro-future-test#35]
特别是“走入顾客”此按钮，点击之后就不知道如何操作了，是否为功能未完成？

**Comment by guanbo** [comment]
@chenshun @xiaoyuxiong 针对 @MengWei 的说法是否有同样感受？

**Comment by chenshun** [comment]
我不明白的是点击`走入顾客`具体要实现什么功能，是不是点击`走入顾客`之后应该变成`会员`？
我在刚开始进入收银界面的时候也不知道该怎么操作，胡乱操作了很久才找到一点门道。

**Comment by MengWei** [comment]
我觉得“走入顾客”应该是和会员相关的操作，例如：
1、点击后，通过输入会员号，查询到对应会员，然后本次消费可以根据会员策略进行优惠或者积分；
2、点击后，提供新增新会员的入口，方便消费者现场会员办理；

**Comment by guanbo** [comment]
> 1、点击后，通过输入会员号，查询到对应会员，然后本次消费可以根据会员策略进行优惠或者积分；

现在就是这样，UI引导需要调整。

> 2、点击后，提供新增新会员的入口，方便消费者现场会员办理；

这个可以做为新需求单独起一个issue 参加 #36。
