### ISSUE TITLE
POS收银系统，结算过程中先输入“会员储值”再输入“折扣比例”或“折扣金额”，多出的金额会划入“找零”中

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#353]
### 步骤
1. 进入POS收银系统，点击`销售`
2. 输入会员编号，点击`会员`
3. 输入`商品编码`选择销售商品，点击`结算`
4. 选取`会员储值`，输入足够支付的金额
5. 选取`折扣金额`或`折扣比率`，例如`折扣金额`输入`200`
### 结果

这多出来的`200`会显示在账单的`找零`中
### 期望

会员储值支付时多出的金额自动划入会员储值余额中

**Comment by chenshun** [comment]
现在的修改引起两个问题：
- 先输入小的比率。例如`90`，再输入`95`，则多余部分仍会显示在`找零`中
- 输入折扣后，点击两次`确认`使得账单中的`折扣比例`消失

**Comment by puttin** [comment]
> 输入折扣后，点击两次确认使得账单中的折扣比例消失

这个问题是#342

> 先输入小的比率。例如90，再输入95，则多余部分仍会显示在找零中

~~确认存在~~ 好像不存在 显示的是仍需付款的金额
