### ISSUE TITLE
POS收银机设置，在设置后会使登陆界面出现错误

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#357]
### 步骤
1. 打开POS，进入登陆界面
2. 点击右上角`设置`，弹出`收银机设置`窗口
3. 点击`代码`的input
4. 再点击`商户`的input
5. 点击`关闭`
### 结果

登陆界面错误
### 期望

登陆界面正常

**Comment by puttin** [comment]
iOS 6 及 7下均存在
但只存在于有候选栏的输入法
