### ISSUE TITLE
收银对账需要交易明细

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#358]
## 问题

用户在使用中需要对账期内的明细。在对账总计的结果与实际结果不符合，例如前对不上的情况下，需要每笔交易进行核对。主要是在错单的情况，核对那笔交易输入错误造成的金额不对。
## 解决

在收银对账的时候加入明细交易查询的入口，通常情况下只显示摘要数据。有需要的情况下再拉出明细情况。

@chenshun 设计交互原型后 @puttin 实现。

**Comment by chenshun** [comment]
用户查询出某个时间段的交易笔数后，可点击进去查看每笔交易的概要，再次点击可查看整个交易账单。
[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211713/preview)

**Comment by guanbo** [comment]
不建议页面跳转的方式来显示详单，就直接在当前页面中将所有交易罗列在摘要的尾部。

**Comment by chenshun** [comment]
取消页面跳转，将交易账单罗列在查询结果的最下方，点击可以展开每笔账单所出售的商品。
[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211713/preview)

**Comment by guanbo** [comment]
- 需要有结算方式，参见https://projects.invisionapp.com/d/main#/console/292578/12162454/comments
- 对账单打印的功能没有实现，需要支持。

**Comment by chenshun** [comment]
将交易账单罗列在摘要尾部，供用户直接查看。[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211713/preview)
账单的显示顺序应该以时间由近到远依次往下排列

**Comment by guanbo** [comment]
OK, @puttin 请实现。

**Comment by puttin** [comment]
云存储3剩下的时间内恐怕难以实现了

**Comment by puttin** [comment]
云存储4剩下的时间内恐怕难以实现了
