### ISSUE TITLE
POS界面新增会员

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#36]
在POS收银界面提供新增会员功能，这样收银员就可以进行办理会员开卡业务。不需求进入后台管理界面。

**Comment by guanbo** [comment]
@chenshun 请设计原型， @puttin 实现

**Comment by chenshun** [comment]
POS收银界面[新增会员](https://projects.invisionapp.com/d/main#/console/292578/9312138/preview)原型。
