### ISSUE TITLE
销售记录需要快捷全面的展现

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#360]
## 问题
- `查询不便` 现在我们对于销售记录的虽然可以在列表的顶部做模糊搜索，但不是客户想要的形式。客户希望能以时间轴为筛选的依据，快速的查询到当天、结账周期内（通常为一周或一个月）的交易记录。
- `信息不全面` 我们现在的销售报表是面向汇总统计的，虽然销售流水记录展开以后可以看到交易的清单，但用户认为不够全面。希望能看到涉及交易的全部详细信息，方便回顾。
## 对策
- 在管理界面的首页中加入当天和昨天销售记录情况的入口
- 交易记录列表中提供更加直观的，有引导性的搜索入口，例如：本月销售记录、或时间段选择的销售记录。
- 在销售记录中在点击销售记录详情后，可以查看到交易的全部细节，如同POS界面中`流水`中查询出的全部信息。

@chenshun 考虑交互设计后完成原型调整， @puttin 实现

**Comment by chenshun** [comment]
调整如下：
- 在`销售流水记录`中加入`总销售记录`、`今日销售记录`、`昨日销售记录`、`本周销售记录`、`本月销售记录`五个子列表
- 在列表底部增加三个按钮，用来子列表之间的切换，同时可以以时间轴选择时间段进行筛选
- 增加点击交易记录显示该笔交易账单详情功能；

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211684/preview)

**Comment by guanbo** [comment]
> 在销售流水记录中加入总销售记录、今日销售记录、昨日销售记录、本周销售记录、本月销售记录五个子列表
> 在列表底部增加三个按钮，用来子列表之间的切换，同时可以以时间轴选择时间段进行筛选

在 #369 中有类似的意见

> 增加点击交易记录显示该笔交易账单详情功能；

同意

**Comment by chenshun** [comment]
把选择不同时段的功能键移至左上角，[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211684/preview)
同时考虑到以弹窗形式显示交易账单，在切换到下一笔时会有所不便，所以在弹窗中加入`下一笔`，可以直接逐条显示。

**Comment by guanbo** [comment]
有下一笔，必须要有上一笔

**Comment by guanbo** [comment]
@chenshun 请完善原型。

**Comment by chenshun** [comment]
用左右箭头来实现账单详情的切换。
[参考原型](https://projects.invisionapp.com/d/main#/console/292578/12167925/preview)

**Comment by guanbo** [comment]
@puttin 请实现

**Comment by puttin** [comment]
云存储4剩下的时间内恐怕难以实现了

**Comment by chenshun** [comment]
目前自定义时间段无法准确选择一天的销售记录，例如`2014-1-9~2014-1-9`，应该显示1月9日当天销售记录，实则显示为空。
