### ISSUE TITLE
员工业绩分析

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#361]
## 需求

店长和业主出于经营分析的需要，要了解到每个员工的销售业绩。
- 员工时间段总业绩
- 品类要到产品销售的单品也要有分类的情况
- 员工间业绩的横向比较
- 以图表的形式展现

**Comment by guanbo** [comment]
@chenshun 请出原型， @puttin 实现。

**Comment by chenshun** [comment]
原型已出：
- `员工分析`分为`员工业绩分析图表`和`员工销售商品分析`两模块
- `员工业绩分析图表`由员工业绩数据表和计划与实际销售额的ColumnChart组成
- `员工销售商品分析`暂定是把所有销售出去的商品展现，然后按照各个员工所销售的其中所占数量显示

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/13830094/preview)

**Comment by guanbo** [comment]
建议将计划销售额调整为上期销售额，理由有2：
- 需要建立销售计划管理，否则计划的数据没有来源。但这样工作量将新增不少。
- 目前很多中小店还没有引入这样的管理，可以放在后期再丰富销售管理。主要是要先收集下市场方面实际的情况。

**Comment by chenshun** [comment]
OK,请暂时忽略该原型，还有部分需要根据今天对门店部分的修改作出相应调整。
明天早上会给出修改完毕的原型。

**Comment by chenshun** [comment]
原型已经调整：
- `计划销售额`改为`上期销售额`
- 修改选择时间段的方式

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/13830094/preview)
