### ISSUE TITLE
门店业绩分析

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#362]
## 需求

店长可以对商户所属的门店进行经营业绩的分析。
- 单店总业绩趋势分析
- 分类和单品的业绩趋势分析
- 门店间横向比较业绩
- 以图表的形式展现

**Comment by guanbo** [comment]
@chenshun 出原型， @puttin 实现

**Comment by chenshun** [comment]
原型已出：
- 左边主菜单加入`业绩`模块，包含`门店业绩`和`雇员业绩`
- `门店业绩`由两部分组成：`门店业绩统计图`、`商品销售统计图`
- `门店业绩统计图`主要由折线统计图与条形统计图构成
- `商品销售统计图`暂时还是扇形统计图，优点简洁、直观，一个商品一个图；缺点是销售趋势反应不够强

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/13653241/preview)

**Comment by guanbo** [comment]
@puttin @chenshun 已经最原型做出了评论，请查看。所有评论关闭后再进入实现阶段。

**Comment by puttin** [comment]
我之前看过这个原型 等现有的评论关闭后我在提出我的观点吧

**Comment by guanbo** [comment]
@puttin 现在就可以直接在原型上进行评论，而且评论上也是可以跟帖的。

**Comment by chenshun** [comment]
现对原型调整如下：
[参考原型](https://projects.invisionapp.com/d/main#/console/292578/13653241/preview)

**Comment by guanbo** [comment]
@chenshun 原型已经评论，请查看

**Comment by chenshun** [comment]
- 修改了选择时间段的方式
- 舍弃了`Line Chart`

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/13653241/preview)

**Comment by guanbo** [comment]
@puttin 请实现
