### ISSUE TITLE
POS管理界面，“库存汇总表”中反应的数据不能满足用户需求。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#369]
当前版本中的`库存汇总表`只能反应出库存的存量数据，用户的需求是可以分不同的时间段把各个阶段内的数据呈现出来，同时还需要加入`进货数量`的显示，需要重新设计原型。

**Comment by chenshun** [comment]
将原来的`累计库存`改为`进货数量`,**列表底部增加三个功能按键，**用户可以左右切换查看`今日盘点`、`昨日盘点`、`本周盘点`、`本月盘点`、`年度盘点`从而满足对各个时间段库存变化的掌握。同时中间按键可以自己设置时间段。
[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211680/preview)

**Comment by guanbo** [comment]
- 在列表中加入上期库存，如果地方小了就把收入和销售合并在一起，分上下显示。同样的支出和进货合并。
- 建议将底部功能键和顶部的标题栏合并，默认进入是今日盘点，点击标题栏后popover一个列表包含昨日、周、月、年盘点，以及时间窗口选择入口。

**Comment by chenshun** [comment]
- 将`收入`与`销售`、`支出`与`进货`合并分左右显示，因数量与金额位数相差较大，上下显示使数据感觉混乱，不美观
- 将底部功能键移至左上角，通过popover的形式提供选择列表
- 考虑上期库存要显示完整的数据供用户比较，现改为左右直接滑动替换的形式。如果侧重同时显示两张列表，可以考虑分上下显示供用户比较。

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211680/preview)

**Comment by guanbo** [comment]
- 还是要有上期库存，给用户一个参考。及时切换到其他窗口期没有在一个窗口期内比较直观。
- 收入和销售并排后是否会显得过分拥挤，可以请 宗超帮忙出一张高保真看看。

**Comment by chenshun** [comment]
已经加入`上期库存`，其余没有变化。[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211680/preview)

> 收入和销售并排后是否会显得过分拥挤，可以请 宗超帮忙出一张高保真看看。

数据不会拥挤，低保真中的空间显示很乐观。

**Comment by guanbo** [comment]
OK ，请 @puttin 实现

**Comment by puttin** [comment]
云存储3剩下的时间内恐怕难以实现了
