### ISSUE TITLE
在管理界面新增加的商品SKU在收银界面的销售中不显示，并且从管理界面回到收银界面，销售结算的时候多数情况会出现闪退或卡死现象

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#37]
### 步骤
1.  点击`商品`，再点击某件商品后的箭头进入`商品详情`
2. 点击库存右侧`+`，新增库存点击`确定`,再点击`完成`
3. 登出`管理界面，进入收银界面
4. 点击`销售`
5. 输入某商品编码，选择好商品点击`结算`
6. 输入付款金额点击`确认`
7. 点击`结算`
### 结果

出现闪退或卡死情况
### 期望

结算正常

(注：在`结算`的时候经常会挂掉，但是有时候也会正常，找不到必然可以重现该bug的步骤，上述步骤出现该Bug频率最高)

**Comment by guanbo** [comment]
@chenshun 注意markdown语法 order list 数字点和文本见要有空格。

**Comment by puttin** [comment]
@guanbo 这个commit(https://github.com/extensivepro/expropos/commit/bf04a3b128d51ae38cf6aabddb198361b4f8efe2) 除了提高一些效率 看上去和闪退问题应该无关?

**Comment by guanbo** [comment]
未发现闪退。

**Comment by chenshun** [comment]
上面的order lists数字点和文本间有空格：
1. Order list item
