### ISSUE TITLE
POS退货流程收集的一些建议和操作时容易卡主的环节反馈。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#371]
#### 杨月明操作过程中卡主的两个环节：
1. 刚开始退货时不知道输入交易流水号
2. 输入交易号点击退货后不知道选择退货商品
#### 孙娜提的一些建议，整理如下：
1. 退单中需要反映出折扣
2. 退货时，需要收银员手动输入退款以此来确认
3. 退单时间需要显示年月日
4. 收银时会误认为最上端的提示文字是输入框
5. 退单号和已退商品不需要分开显示
#### 两人共同的遇到的问题
- 退货时，商品数量和价格的编辑功能隐藏太深

**Comment by chenshun** [comment]
> #### 杨月明操作过程中卡主的两个环节：
> 1. 刚开始退货时不知道输入交易流水号
> 2. 输入交易号点击退货后不知道选择退货商品

针对容易卡主的两个环节，均存在灰色按钮。**我考虑是否应该弃用灰色按钮??**
       因为不可点击时用户更多是不知所措或者干脆放弃操作，很少会注意提示。所以应该在条件不满足时点击给出相应提示，例如：不输入交易号，`退货`可以点击，点击之后跳出提示`请输入交易号`。这样可以给用户一定的引导。

**Comment by guanbo** [comment]
> 杨月明操作过程中卡主的两个环节：
> 
> 刚开始退货时不知道输入交易流水号
> 输入交易号点击退货后不知道选择退货商品
> 针对容易卡主的两个环节，均存在灰色按钮。我考虑是否应该弃用灰色按钮??
> 因为不可点击时用户更多是不知所措或者干脆放弃操作，很少会注意提示。所以应该在条件不满足时点击给出相应提示，例如：不输入交易号，退货可以点击，点击之后跳出提示请输入交易号。这样可以给用户一定的引导。

同意， @puttin 请实现

> 退单中需要反映出折扣
> 退货时，需要收银员手动输入退款以此来确认
> 退单号和已退商品不需要分开显示

分别用单独的issue来解决

> 退单时间需要显示年月日
> 收银时会误认为最上端的提示文字是输入框

这两块需要再收集下其他的意见

> 退货时，商品数量和价格的编辑功能隐藏太深

在商品数量和价格栏的位置用颜色或外观来和其他项目区分出来。另开issue解决。

**Comment by puttin** [comment]
并不是很紧急的问题, 暂不在云存储3中解决吧

**Comment by puttin** [comment]
暂不在云存储4中解决
