### ISSUE TITLE
销售和退货过程中，商品价格和数量可以编辑的地方需要通过外观或颜色给用户提示。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#372]
目前在销售和退货时，商品的数量和价格均可调整，但是该功能隐藏较深，用户普遍难以发现。
**需要通过外观或者颜色给用户一点提示。**

**Comment by puttin** [comment]
右上角不是有操作提示了么 外观或者颜色上提示的话我的审美会弄得更丑的

**Comment by guanbo** [comment]
- 可以考虑在输入的地方加入一个笔型的icon提示可以编辑。
- @puttin 可以给些建设性意见。

**Comment by puttin** [comment]
如果添加图片之类的 空间可能不够

可以考虑更改字体颜色?

**Comment by guanbo** [comment]
这块暂缓，考虑到合适的方案再动手。

**Comment by puttin** [comment]
并不是很紧急的问题, 暂不在云存储3中解决吧

**Comment by puttin** [comment]
暂不在云存储4中解决
