### ISSUE TITLE
POS中的身份证校验，在各种错误的情况下，提示均一样，需要细分给用户以引导

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#374]
在新增会员、新增雇员时，需要填写正确的身份证号才可通过。实际操作中，用户会遇到很多输错的情况，而错误的提示单一，不能正确引导用户修正，因此需要对各种错误情况细分，准确提示用户。

**Comment by guanbo** [comment]
四川客户曾用以下身份证51150219890617511X登记雇员，但其实该身份证号的校验码应该为2，我们的提示比较模糊。好在客户电话咨询我们最后解决。但类似情况发生在自行尝试的用户上将很有可能造成用户放弃。
