### ISSUE TITLE
POS在进货时的建议

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#375]
进货一种商品完成后，需要再次点击左上角`+`才能继续进货。而实际使用时，会习惯性的立刻再去扫条码，忽略了点击进货。建议在进货列表可以直接扫条码打开进货窗口，增强体验。

**Comment by guanbo** [comment]
这是连续进货的场景，可以考虑不光是有扫描枪的情况，还要考虑无枪情况下的连续进货。 @chenshun 请设计交互体验，然后由 @puttin 实现。

**Comment by chenshun** [comment]
在确认进货信息的弹窗中增加一个`好，继续`的功能键。
[参考原型](https://projects.invisionapp.com/d/main#/console/292578/8443573/preview)

**Comment by guanbo** [comment]
建议用`好，进下一件`
