### ISSUE TITLE
POS打印账单时需要对打印次数加以限制。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#376]
POS在销售过程中，打印机可能暂时连接不上无法打印。
在这种情况下，用户会**多次点击打印**，当打印机连接之后，会打印出一长串账单。
因此需要对打印的次数加以限制，即无论用户怎么点击`打印`，一次一张账单最多打印两张

**Comment by guanbo** [comment]
考虑再打印开始后，3秒内打印按钮不可用。显示正在打印。

**Comment by puttin** [comment]
> 3秒内打印按钮不可用。显示正在打印

这种情况并不能解决3秒后继续点一下打印 最后还是打一长串的问题吧

**Comment by guanbo** [comment]
> > 3秒内打印按钮不可用。显示正在打印
> > 这种情况并不能解决3秒后继续点一下打印 最后还是打一长串的问题吧

的确没办法解决，但会好点。或者你又更好的建设性意见？

**Comment by puttin** [comment]
并不是很紧急的问题, 暂不在云存储3中解决吧

**Comment by puttin** [comment]
暂不在云存储4中解决
