### ISSUE TITLE
新增员工的时候员工编号重复

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#377]
## 问题
- 在新增员工的时候员工编号永远是3
- 在编辑的时候如果不改3会出现看不见的错误提示
## 预期
- 员工编号可以自增
- 出现重复员工编号的时候错误提示可以看见

**Comment by puttin** [comment]
员工编号永远是3无法重现
错误提示看不见和#391 原因相同 已在#391 中修复

**Comment by chenshun** [comment]
在离线操作时，该BUG无法重现。接入网络后，仍然存在该问题。

**Comment by puttin** [comment]
但是我看了下代码方面的同步的逻辑应该不影响这里
@guanbo 有什么可能的原因嘛?
