### ISSUE TITLE
关于销售商品汇总表，是否应该只显示销售出去的商品

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#378]
现在的`销售商品汇总表`把所有的商品都罗列出来，是否恰当？
我考虑是否应该只显示销售出去的商品？  @guanbo  @puttin

**Comment by guanbo** [comment]
- 可以考虑做个排序，有销量的在前，没有销量的在后；
- 没有销量的按名称排序。

**Comment by puttin** [comment]
> - 可以考虑做个排序，有销量的在前，没有销量的在后；
> - 没有销量的按名称排序。

也就是说还是显示全部商品, 但是销量排序优先, 名称排序其次是吗

**Comment by guanbo** [comment]
是的
