### ISSUE TITLE
支持离线操作

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#379]
在没有网络的条件下，操作的数据保存在本地，待在线的时候再与服务器同步。

**Comment by guanbo** [comment]
已经在当前版本 08fab0e77865f87226cd10974e8486e0cead9a37 以后解决。请陈顺重点测试数据是否会不能同步上来。

**Comment by chenshun** [comment]
我关闭网络，修改会员资料、商品状态，然看再连接网络，放置了大概5min，然后执行同步，得到的数据是未作修改前的。

**Comment by guanbo** [comment]
> 放置了大概5min，然后执行同步，
- 是否重新打开应用？
- 到设置中打开商户列表界面？

**Comment by chenshun** [comment]
> - 是否重新打开应用？

只是放置在一边，并没有关闭应用，所以没有重新打开

> - 到设置中打开商户列表界面？

是的

**Comment by chenshun** [comment]
离线操作时的销售记录是可以同步上来的，单是对商品、会员信息的修改无法同步。

**Comment by guanbo** [comment]
应该基础信息和交易信息都可以离线同步，可能是由于只有当软件从内存中清除后重新启动才会去同步，造成的假象，已经调整为每次打开应用都会去尝试上传离线数据。
