### ISSUE TITLE
POS同步得到的商品库存为空，进货记录信息不全。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#381]
### 步骤
1. 进入POS管理系统，完成一笔进货
2. 删除该应用，重新下载
3. 打开新下载的POS，进行云端同步
4. 同步完成后进入管理系统，查看商品以及进货记录
### 结果

`库存汇总表`中所有商品数量为空，进货记录显示的信息不全
### 期望

实现完美同步

**Comment by guanbo** [comment]
- [x] 补齐进货支出
- [x] 补齐经办人
- [x] 删除以后同步不会再显示
