### ISSUE TITLE
POS管理系统，登记的商品在执行过同步后会变为两条

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#382]
### 步骤
1. 进入POS管理系统
2. 点击`商品`，登记一笔新商品
3. 删掉POS，重新下载
4. 进行云端同步，查看刚才登记的商品信息
### 结果

变成两条一模一样的数据
### 期望

同步之后，数据正常

**Comment by chenshun** [comment]
补充:进货新商品也会出现该bug，并且这条进货记录会消失。

**Comment by guanbo** [comment]
已经在 ac2d23bcefc50cdc013b3df8414452da2caa1f3d 以后修复
