### ISSUE TITLE
商品标记删除会引发的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#383]
商品删除之后，则无法重新进货、上架，因为商品编码已经存在。
这会给用户以后造成困扰。

**Comment by chenshun** [comment]
可以考虑在下次进货时，直接带出商品信息，但是去除该商品之前的库存，只生成一个新的库存

**Comment by puttin** [comment]
现考虑首先输入完编码或者扫码完后查询相关商品, 查询到自动补充
#324

**Comment by chenshun** [comment]
进货一批新商品，状态为`上架`，但未输入`出售价格`时，应该提示用户输入`出售价格`。
