### ISSUE TITLE
POS新增进货之后，同步得到的进货记录没有商品名

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#384]
### 步骤
1. 进入POS管理系统
2. 点击`进货`，完成一笔进货
3. 删除应用，重新下载并且同步数据
4. 进入POS管理系统，查看进货记录
### 结果

原来的进货记录商品名称消失，并且获取不到新增的进货记录
### 期望

显示原有商品名，显示最新进货记录

**Comment by guanbo** [comment]
已经在 ac2d23bcefc50cdc013b3df8414452da2caa1f3d 以后修复。
