### ISSUE TITLE
POS的云端账户登陆界面无法返回上一步

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#385]
### 步骤
1. 打开POS，点击`设置`
2. 点击商户，进入到云端账户登陆窗口
### 结果

这个登录窗口无法返回到之前的界面，如果没有云端账户，则会困在这里
### 期望

可以返回到之前的界面

**Comment by guanbo** [comment]
在 5ab3bab6ccbbbdcedf685000a84f9f268fe636a0 调整流程以后不存在上市问题
