### ISSUE TITLE
雇员离职后，显示的离职日期错误

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#387]
### 步骤
1. 进入POS管理系统，点击`雇员`
2. 选择一名雇员，将他离职
3. 查看该雇员离职时间
### 结果

离职日期总是显示`45897-xx-xx`
### 期望

显示正确日期

**Comment by puttin** [comment]
怀疑是同步造成的@guanbo 
离线环境下模拟器真机测试无法重现
在线时可以重现

**Comment by guanbo** [comment]
已经在 ac2d23bcefc50cdc013b3df8414452da2caa1f3d 以后修复
