### ISSUE TITLE
商品库存云端同步，当销售数量变化时，得到的数据不正确

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#388]
### 步骤
1. 进入POS收银系统，选择一件商品销售
2. 进入管理系统，查看刚才商品在库存汇总表中的信息
3. 删除POS，重新下载，并完成同步
4. 重新查看刚才的商品库存信息
### 结果

该商品的`销售数量`与`收入`发生变化
### 期望

同步得到的数据正确

**Comment by guanbo** [comment]
可能引起的边际效应
- 交易登记商品的时候失去最大库存纠正。
- 退货调整退后数量的时候失去最大交易数量纠正。
