### ISSUE TITLE
把雇员从离职状态改为在职，有时会使整个雇员列表变成空白

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#389]
### 步骤
1. 进入POS管理系统，把雇员设为离职
2. 再把雇员设为在职
3. 如此反复
### 结果

会出现雇员列表变成空白的情况
### 期望

杜绝该情况的发生

**Comment by guanbo** [comment]
@chenshun 最好给出规律方便定位问题。

**Comment by chenshun** [comment]
把离职会员设为在职时候会出现该BUG，并不是每次都出现。附图一张：
![image](https://f.cloud.github.com/assets/3068259/1681419/4bf8fd7e-5d93-11e3-8e43-5f100e612a4d.png)

**Comment by puttin** [comment]
无法重现

**Comment by puttin** [comment]
怀疑是同步造成的
后来出现过嘛? @chenshun

**Comment by guanbo** [comment]
遇到过，reloadData以后可以正常显示。

**Comment by guanbo** [comment]
#414 和这个问题放到后面一并解决。主要是监听CoreData ManagedObjectContext容易引起多长的refresh。
