### ISSUE TITLE
管理界面，会员详情中点击“编辑”后无法"存储"

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#39]
### 步骤

1.点击`会员`
2.点击`会员`后面的箭头进入`会员详情`
3.点击`编辑`
4.点击`存储`
### 结果

没有反应
### 期望

存储成功

**Comment by puttin** [comment]
无法保存是因为数据有误

种子数据中的 `320103022012312018` 身份证号不符合身份证标准 最后一位应该为`7` 即 `320103022012312017`

数据有误应该如何提示用户? @guanbo 
1. 晃动UITextField 无边框不知是否能看出来效果
2. 给错误UITextField加红色边框
3. 加红色边框并抖动

**Comment by guanbo** [comment]
> 1. 给错误UITextField加红色边框

用这个

> 种子数据中的 320103022012312018 身份证号不符合身份证标准 最后一位应该为7 即 320103022012312017

身份证规则是为数不能为8？如果是，我讲调整开局数据。

**Comment by puttin** [comment]
> 身份证规则是为数不能为8？如果是，我讲调整开局数据。

不是, 最后一位是根据前面的计算出来的校验用的 @guanbo

**Comment by chenshun** [comment]
即使数据正确，例如输入`320103022012312017`，当保存一次之后再进行编辑，也无法保存
