### ISSUE TITLE
会员和雇员中的身份证号，在编辑的时候没有错误提示

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#391]
### 步骤
1. 点击`雇员`，选择一名雇员进入`雇员详情`
2. 点击`编辑`，把身份证号改成一个错误的号码
3. 点击`保存`
### 结果

有红色边框，但是并未出现错误提示。并且还可以将号码置空。
### 期望

出现相应提示，并且雇员身份证不可置空

**Comment by puttin** [comment]
确定是iOS7造成的
iOS6下正常
