### ISSUE TITLE
未选择商户前进行的操作会对同步后的商户产生影响

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#392]
### 步骤
1. 下载泛商会POS，进入管理系统新增商品或会员
2. 登出POS，设置商户，同步云端数据
3. 进入POS收银系统
4. 点击`销售`，输入刚才新增的商品编码
### 结果

可以看到刚才新增的商品
### 期望

未选择商户前进行的操作，不应该影响到该商户

**Comment by guanbo** [comment]
https://github.com/extensivepro/expropos/commit/8efbdcf052b243150d86c359229d7568eb36f517 Fixed
