### ISSUE TITLE
库存报销

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#395]
商品库存需要有报销入口，店长可以在后台管理界面对商品的库存进行报销处理。
- 报销处理的类型要区别于交易
- 报销处理不产生账单

@chenshun 设计原型， @puttin 实现。

**Comment by chenshun** [comment]
原型修改如下：
- 在进货入口`+`左边加入`－`为出货功能
- 进货列表改为`库存记录`
- 进货数量显示为`+quantity`，出货显示为`－quantity`；进货时输入的金额显示为`－￥`,出货输入显示为`+￥`;进货和出货的金额都应为选填
- `进货说明`改为`备注`

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/9704135/preview)

**Comment by chenshun** [comment]
建议早点让宗超出新界面，把按键扁平化，然后可以把各个列表标题放在左边，所有的按键移至右边。

**Comment by guanbo** [comment]
@chenshun 原型有一处需要调整
@puttin 请实现功能

**Comment by puttin** [comment]
云存储4剩下的时间内恐怕难以实现了
