### ISSUE TITLE
会员充值或积分变更后，会员信息不能及时更新，且总是会对之前数据产生影响

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#398]
### 步骤
1. 进入POS收银系统，点击会员，查看会员列表
2. 新增一名会员，此时会员`积分`与`储值金额`都为零
3. 进入收银系统，点击`会员`
4. 输入刚才新增的会员编码，充值`1000`金额，`100`积分
5. 返回管理系统，查看会员信息
### 结果

该会员储值金额显示`0`
### 期望

充入`积分`后不会使金额产生变化

**Comment by puttin** [comment]
离线操作无法重现 怀疑是同步造成
@guanbo @chenshun

**Comment by chenshun** [comment]
现在储值金额不会发生变化，但是积分始终是`0`

**Comment by guanbo** [comment]
问题是由服务器端程序没有更新而引起，现在已经更新。
