### ISSUE TITLE
切换商店时反应很慢，点击多次后切换成功，之后会一直弹出提示成功

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#399]
### 步骤
1. 在登陆界面点击`设置`
2. 点击商户，输入云端账户，点击`登录`
3. 点击`添加新商店`，完善信息，点击存储
4. 选择新开店铺
### 结果

点击之后等待时间较长，如果多次点击，之后离开设置界面也会弹出`成功`提示
### 期望

其他界面不会弹出提示

**Comment by guanbo** [comment]
9c36bee347b200b93b9409cad33cf9a3b6b4416a 已经解决
