### ISSUE TITLE
会员身份识别支持刷卡方式

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#407]
## 需求

收银界面目前是采用手动输入会员卡号，要支持通过音频口来刷磁条卡读取会员卡号。
## 任务

利用音频口刷卡器，在收银会员登记界面和消费界面支持刷卡识别会员。
## 备注

目前音频口刷卡器已经经过测试。

**Comment by puttin** [comment]
虽然标记`done` 了 但可能会不稳定, 测试时候如果发现有什么规律性的问题请留言

**Comment by guanbo** [comment]
程序进入后台以后，再次进入时候会闪退。
