### ISSUE TITLE
POS目前同步无法得到新增加的进货记录和进货商品数量

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#410]
### 步骤
1. 打开POS，点击`进货`
2. 完成一笔进货，查看商品数量、进货记录
3. 删掉POS，重新下载，并且完成同步
4. 查看商品数量、进货记录
### 结果

商品数量为`0`，进货记录消失
### 期望

能够得到商品数量与进货记录

**Comment by guanbo** [comment]
Build 34 版本未重现。
