### ISSUE TITLE
新增一名会员会使整个会员列表暂时消失,reloadData之后才会正常显示

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#414]
### 步骤
1. 进入POS管理系统，点击`会员`
2. 上下滑动一下会员列表
3. 点击`+`，完善信息，新增一名会员
4. 点击`创建`
### 结果

可以看到整个会员列表变空了，过几秒后才会出现
### 期望

直接显示

**Comment by guanbo** [comment]
与 #389 重复，请关闭
