### ISSUE TITLE
新注册的云端账户，建议在用户登陆后引导用户自己创建商户

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#417]
创建完云端账户，登陆进去后就直接停留在`商户商店设置`的界面，并且会跳出`商户名已经被使用`的提示。
建议在用户第一次登录云端账户，直接进入商户设置界面，完善商户信息存储后才能进行商户商店设置。

**Comment by guanbo** [comment]
收费版本，不允许出现注册界面。所讲调整为不用注册，用户直接改信息的模式。

**Comment by chenshun** [comment]
始终觉得直接改信息模式虽然简单，但是不符合时下用户的潜意识。
