### ISSUE TITLE
 新注册的云端账户，在同步时会出现“udid is duplicated”的提示

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#418]
### 步骤
1. 新下载POS，在登陆界面点击`设置`
2. 点击`商户`，注册一个云端账户，并且登陆
3. 设置商户信息，然后`存储`
### 结果

存储后返回设置界面进行同步，然后提示`udid is duplicated`
### 期望

正常同步

**Comment by guanbo** [comment]
在 https://github.com/extensivepro/expropos/commit/c37c2951d44c2ed489a187e4a57e5c79ebe7464e 以后无法复现。

**Comment by chenshun** [comment]
仍然可以复现。
需要新注册一个云端账户，然后同步时才会出现该BUG。
已经更改了Issue名字：

> 新注册的云端账户，在同步时会出现“udid is duplicated”的提示
