### ISSUE TITLE
POS新增会员时，会跳出提示“dueAt It sinceAt”

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#420]
### 步骤
1. 进入POS管理系统，点击`会员`
2. 点击`+`,完善会员资料，点击`创建`
### 结果

提示`dueAt It sinceAt`
### 期望

可以正常创建会员

**Comment by guanbo** [comment]
已经在 https://github.com/extensivepro/expropos/commit/c37c2951d44c2ed489a187e4a57e5c79ebe7464e 中解决。
