### ISSUE TITLE
在商户商店设置中，无论是查看商店信息或是取消操作，都会有一次"同步数据成功"的提示

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#424]
### 步骤
1. 打开POS，进入登陆界面
2. 点击`设置`，选择商户，进入云端账户登陆界面
3. 输入密码，点击登录，系统自动同步
4. 同步后随便查看一家店，进入商店设置界面
5. 返回到`商户商店设置`
6. 点击`添加新商店`
7. 再次返回`商户商店设置`
### 结果

第5步与第7步都出现`同步数据成功`的提示
### 期望

提示只会出现在用户切换店铺或是新增、编辑商店之后，对于查看或是取消的操作，不应该出现提示。

**Comment by guanbo** [comment]
目前设计的就是每次回到商户商店设置的界面自动同步一次数据。

考虑到这个操作不是经常性的操作，所有放到后面调整。

**Comment by guanbo** [comment]
重构了注册流程
