### ISSUE TITLE
会员消费时，默认的支付方式需要调整

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#428]
### 步骤
1. 进入POS收银系统
2. 点击销售，输入会员编号，选择`会员`
3. 输入商品编码，点击`结算`
### 结果

此时默认结算方式为`现金付款`
### 期望

会员结算时默认交易方式为`会员储值` （//使用时经常忘记切换到会员储值，导致会员没有扣钱，现金也没有收）

**Comment by chenshun** [comment]
另外建议支付方式左边的`折扣金额`默认为`折扣比率`，因为折扣比例总是比现金折扣要更加常用

**Comment by guanbo** [comment]
@puttin 完成上面的工作。

> 另外建议支付方式左边的折扣金额默认为折扣比率，因为折扣比例总是比现金折扣要更加常用

需要再讨论。

**Comment by puttin** [comment]
暂不在云存储4中解决

**Comment by puttin** [comment]
> 建议支付方式左边的折扣金额默认为折扣比率，因为折扣比例总是比现金折扣要更加常用

我也觉得比例更常用一些

**Comment by chenshun** [comment]
同时会员储值支付时，应该默认扣除账户余额，直接可以结算，不需要用户再手动输入一遍。
