### ISSUE TITLE
同步得到的商品库存是整个商户范围的

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#431]
##### 前提条件

一个商户下有至少两家商店
### 步骤
1. 打开POS，进入`商户商店设置`，选择一家店铺，例如`A店`，完成同步
2. 进入POS管理系统，完成一笔`进货`，查看商品库存
3. 登出，重新进入`商户商店设置`，选择另一家店铺，例如`B店`，完成同步
4. 进入POS管理系统，查看商品库存
### 结果

可以看到`B店`中有`A店`的商品库存
### 期望

同步可以得到商品，但是不会有其他店铺的库存

**Comment by guanbo** [comment]
@puttin 是由于在商品库存汇总表统计销量等数据的时候没有加入当前商店的条件限制，所有会显示所有销量数据。由于 #369  要调整汇总表，所有请你修正上述问题。

**Comment by guanbo** [comment]
这个问题要优先解决，年前我会发布云端版本。

**Comment by puttin** [comment]
`库存汇总表`没法弄啊
统计的是商户级别的商品

**Comment by guanbo** [comment]
- 同步商户范围内的商品没有问题
- 库存汇总表统计是商店的库存

**Comment by puttin** [comment]
我没懂你意思 难道库存汇总表只显示挂在商店下面的商品? 那可能一个都没

**Comment by guanbo** [comment]
> 我没懂你意思 难道库存汇总表只显示挂在商店下面的商品? 那可能一个都没
- 我们POS的管理视角是一个商店，你可以看到的并管理的数据仅包括本店数据，不会看到其他家店的库存情况。
- 全商户共享的数据，例如商品目前暂时考虑也是可以管理，后面会对权限进行分级。

**Comment by puttin** [comment]
那我没法弄啊 你商品都挂在商户下面 我光显示本店可能什么商品都没 要是显示商户级别 的就会出现两个店商品都显示

**Comment by puttin** [comment]
可能之前涉及到统计的地方都有这个问题
