### ISSUE TITLE
商品的退货数量可以大于销售数量

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#432]
### 步骤
1. 进入POS收银系统，点击`销售`
2. 选择顾客，例如`普通`
3. 输入商品编码，选择销售商品
4. 点击`结算`，输入付款金额，完成结算
5. 点击`流水`，输入刚才的交易流水号
6. 点击`退货`，编辑数量大于目前值
### 结果

即使退货数量大于销售数量仍然可以退货
### 期望

退货数量只能`<=`购买数量

**Comment by chenshun** [comment]
目前商品销售数量也不受库存影响，即使库存只有`1`，在销售时也可以调整为1以上

**Comment by guanbo** [comment]
@puttin 这个问题是由于同步远程数据的时候，在model层取消了和SKU直接的约束。因为那个约束会营销到RestKit的Mapping。

**Comment by chenshun** [comment]
@puttin 退货数量已经解决，销售数量的情况任然存在。例如：商品库存为2，销售时数量可以大于2。

**Comment by puttin** [comment]
我记得以前这种情况是不存在的啊… 上周五(2014-01-10)我特意去翻相关 commit 好像也没找到哪里改了
