### ISSUE TITLE
会员生日提醒

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#436]
- 在会员信息中单独记录会员生日，因为有的地方会员不提供身份证信息。
- 店长登录到管理界面后，在首页会有一项今天过生日的会员数量。通过这个数量入口可以查看到全部过生日会员的列表和详细信息。

@chenshun  请完成原型设计

**Comment by chenshun** [comment]
原型修改如下：
- 新增会员时，原本`电子邮箱`改为`生日`
- 首页显示会员总数的表格中在当天有会员生日时提醒，提醒可点击，弹出会员生日提示窗口

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/9703208/preview)

**Comment by guanbo** [comment]
email要保留，生日也要。其他没有问题。
