### ISSUE TITLE
会员详情界面重构

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#437]
用户提出希望能查看这个会员的消费记录，在会员界面中。考虑目前会员界面的状况，计划调整会员详情界面将包含下面要素：
- 会员基本信息
- 会员消费记录，最近5条
- 会员储值记录，最近5条
- 可以考虑弹出页面或者替换当前会员列表页面的形式实现。

@chenshun 设计原型

**Comment by chenshun** [comment]
原型修改如下：
- 替换会员列表后面箭头，点击会员资料就会切换到会员详情
- 会员详情不再是左移出现，而是以替换当前列表的方式展现
- 会员详情中加入`出生`和`消费记录`

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211688/preview)

**Comment by guanbo** [comment]
- `出生` -> `生日`
- 消费记录和储值记录并列放每个项目的内容会很少，建议放到全宽度，消费与储值上下布局。

**Comment by chenshun** [comment]
> - 消费记录和储值记录并列放每个项目的内容会很少，建议放到全宽度，消费与储值上下布局。

已经改为上下布局，同时消费记录加入`流水号`，但是储值记录没有流水号，可能上下不对称。
[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211685/preview)
