### ISSUE TITLE
进货时的成本建议改为进货单价

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#440]
鉴于用户在录入进货信息时，都是对照进货单，而进货单只注明单价，所以建议调整成本为`单价`；
进货时出售价格为单价，进货成本也应该是单价。

**Comment by puttin** [comment]
@guanbo 你怎么看

要是这么调整 历史数据要迁移

**Comment by puttin** [comment]
我记太清之前讨论的结果了…
是否是:
调整为 单价 总价都显示
填那个自动补全另一个
?

@guanbo @chenshun

**Comment by guanbo** [comment]
是的

**Comment by guanbo** [comment]
#461
