### ISSUE TITLE
为了安全起见，建议每次程序退到后台后，再次打开都返回到登陆界面

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#441]
优点是可以确保收银安全性，但是缺点也很明显，会造成很多不必要的操作，影响体验。

**Comment by puttin** [comment]
其实现在的安全性巨差…

**Comment by guanbo** [comment]
造做，要给客户体验上感觉安全。

**Comment by puttin** [comment]
就和支付宝之前那个手势锁一样…纸糊的一样

---

确认一下一些逻辑, 一步一步说. 第一个问题:
是只允许之前用户登录 类似电脑的锁屏状态, 还是允许所有用户登录?

**Comment by guanbo** [comment]
默认是之前用户，可以选择其他用户。
