### ISSUE TITLE
当有新的收银结算完成后，库存汇总表中的盘点不会自动更新数据

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#444]
### 步骤
1. 进入POS管理系统，点击`库存汇总表`，查看日盘点
2. 切换到收银系统，完成一笔销售结算
3. 回到管理系统，再次查看日盘点
### 结果

刚才的交易未能反应在列表中
### 期望

每次有新交易产生，都会自动更新列表

**Comment by puttin** [comment]
模拟器下无法重现 可以自动更新
