### ISSUE TITLE
进货记录存在复制成多条的情况，导致库存数量等也产生变化。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#445]
目前未能确定具体重现步骤，重复的进货记录都是昨天的记录，可能与时间有关？
我在新商户中加了几条进货记录，明天再看看变化。

**Comment by chenshun** [comment]
今天在第一次同步时，重现了该BUG，但是之后再确认又不能复现。

### 步骤
1. 进入POS管理系统，查看进货记录（//确认没有重复记录）
2. 登出系统，打开设置，登陆云端账户
3. 等到提示`同步数据成功`，再次选择`总店`
4. 点击`关闭`，进入POS管理系统
5. 点击`进货`，查看进货记录

### 结果

部分进货记录变成两条

**Comment by chenshun** [comment]
目前可以确定：
- 只有新增的进货记录会出现重复，以前的或是以前已经重复过得不会再出现重复情况。
- 同步后才会出现重复。

**Comment by guanbo** [comment]
尚未摸索到规律重现。

**Comment by chenshun** [comment]
暂时关闭，我会继续跟踪，以后出现再reopen。
