### ISSUE TITLE
Mini控制终端连接不稳定

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#447]
## 问题

Mini控制终端在iPad休眠以后会无法找到打印机，同时扫描枪也会失效。只有在重新打印测试页完成以后才可以。
## 期望

可以保持mini终端连接的稳定性。

**Comment by chenshun** [comment]
目前进货过程中，经常会出现扫描枪失效的问题。需要进入setting界面，重新连接才能扫描。
