### ISSUE TITLE
POS收银系统，支付方式中默认的“折扣金额”应该用“折扣比率”替换

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#450]
因为日常生活中`折扣比率`应该更加常用，而且换一次折扣方式需要连续点击两次，这样可以避免用户一些操作。

**Comment by puttin** [comment]
@guanbo 的想法是利用数据追踪的方式, 如果用户折扣使用`比率`较多, 我们就自动显示`比率
`, 如果`金额`较多, 就自动显示`金额`

**Comment by chenshun** [comment]
Perfect.
