### ISSUE TITLE
雇员列表中，修改了业主名称后，左下角的显示不会自己变更

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#453]
### 步骤
1. 进入POS管理系统，点击`雇员`
2. 选择店长，打开详情
3. 点击`编辑`，修改店长名字，`保存`
4. 点击`完成`，查看左下角店长名
### 结果

可以看到店长名称没有变化
### 期望

及时更新

**Comment by puttin** [comment]
原因是走设置处修改会监视, 但是在雇员页面修改现在不会监视…这需要考虑一个更好的方案
