### ISSUE TITLE
POS收银时，一笔没有结算的账单会在销售流水记录中出现

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#455]
### 步骤
1. 进入POS管理系统，点击`销售流水记录`
2. 切换到收银系统，输入会员编码或直接点击`普通`
3. 输入商品编码，选择销售商品，点击`结算`
4. 直接返回管理系统
### 结果

可以看到，销售记录中出现一笔不完整的销售记录
### 期望

没有结算的交易，不会影响销售记录列表

**Comment by puttin** [comment]
现在情况是保留在收银页面, 切换到查流水,会员会提示放弃订单
但是切换回管理页面不会提示…需要提示
