### ISSUE TITLE
建议进货时，扫描条码后，自动跳转到输入商品名称框内

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#461]
进货时，一般扫描条码后就需要输入商品名称了，每次手点较麻烦，建议直接跳到输入商品名称的地方，便于进货操作。

**Comment by guanbo** [comment]
重新设计进货的流程， @chenshun 出原型， @puttin 实现。

**Comment by chenshun** [comment]
新的进货流程已经设计完毕，改动如下：
- 原本左侧菜单中`进货`改为`进销存`，因为加入了`冲销`功能
- 进销存列表中去掉`金额`、`备注`，加入`编码`
- 进货流程主要分为两个必要步骤“确定商品编码”和“输入必填信息”以及一个可以由用户自己选择的步骤"完善商品信息"

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/9704135/preview)

**Comment by guanbo** [comment]
原型新写了些评论，没有问题 @puttin 就进行实习。
