### ISSUE TITLE
新创建的云端账户，在做完一笔销售，切换店铺再查看交易记录时， 原来的记录发生变化

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#463]
### 大致步骤如下：
1. 下载POS，打开进入登陆界面
2. 点击`设置`，注册云端账户，并且登陆
3. 创建商户、商店，并且完成同步
4. 进入POS收银系统，完成一笔交易
5. 进入管理系统，查看刚才的交易记录
6. 登出系统，进入登陆时的设置界面
7. 输入云端账户，新增一家店铺，完成同步
8. 进入POS管理系统
9. 登出，重新选择之前的店铺
10. 进入该店铺的管理系统，查看之前的交易记录
### 结果

可以看到，交易记录详情中商品信息消失了
### 期望

销售记录正常

//PS:考虑重现步骤较复杂，发生条件较苛刻（只有默认的初始数据会发生该情况，并且只会发生在新建的云端账户上，且只会出现一次）暂时可以搁置该BUG。

**Comment by guanbo** [comment]
业务流程已经调整，上述问题不适用了。
