### ISSUE TITLE
删除进货记录使得商品库存也会消失

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#464]
目前删除进货记录，会使相应的商品库存同时减少。这样做是否合理？
我建议删除进货记录并不会影响库存。

**Comment by guanbo** [comment]
- 商品库存的计算是基于进货记录的，也是账面上的库存。
- 后期会有库存盘点，会实际清点库存商品数量并记录。但同时也需要和账面库存做比较。
