### ISSUE TITLE
首次使用导航

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#466]
## 问题

多次被提及首次使用不会登陆的情况。
## 期望

有导航指引帮助用户快速上手的指导程序。

**Comment by chenshun** [comment]
我觉得POS初次使用的时候缺少一定的代入感，因为无需注册、输入账户名就可以直接登录，可能会让刚使用的人产生**“这不是我的东西，我该怎样创建、登录我自己的账户？”**类似的疑问。单就目前登陆而言，应该不存在不会登陆的人吧？

**Comment by puttin** [comment]
现在找设计师出图来不及了吧
