### ISSUE TITLE
离线版本不支持新增会员

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#469]
目前离线版本不支持新增会员，在实际使用时，会给用户带来不便。
建议离线版本加入新增会员功能。

**Comment by chenshun** [comment]
同步之后的店铺在离线时无法新增会员。

**Comment by puttin** [comment]
测试发现新建会员后 会员列表不会自动刷新

**Comment by puttin** [comment]
暂定 离线时还是不允许新建会员 主要原因是会员是基础数据 要考虑会员编号重复手机号重复这种问题

**Comment by puttin** [comment]
@guanbo 那为何商品的编码重复什么的不用考虑?

**Comment by guanbo** [comment]
商品其实也是要避免编码重复，只是有很多实物商品在出厂就有编码，非标产品通常自己会有一套编码规则，暂时没有出现严重的问题。其实编码唯一性可以由客户自己保重，当编码重复的时候允许客户自己在后面修正就可以。

**Comment by puttin** [comment]
那会员这里还是允许保存? 总觉得不稳妥
