### ISSUE TITLE
对账功能下问题，其中有闪退

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#47]
1.进入对账页面，输入开始时间无引导，不知道在哪里输入，且不知道日期格式；个人觉得点击开始时间应该出日期控件方便选择；
2.在开始时间下，输入*_**年__月_*日，点确认按钮，闪退

**Comment by guanbo** [comment]
- [x] 闪退与 #44 重复。
- [x] 日期控件放到下个版本考虑。已经在 #98 实现
