### ISSUE TITLE
库存盘点

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#471]
## 需求

在每个销售的周期末尾，需要对库存中商品进行盘点获得实际库存数量。方便与账面上的库存数量进行对比。
## 期望
- 方便的营业员在盘点时候的工作，拿iPad盘库存的时候可以做到最少的输入。
- 盘点完以后可以形成当期库存汇总表，汇总表的数据作为下期期初的库存的账面数据。
- 完成当前库存的时候可以自动计算出与上期库存的差额，并可以从汇总表进行库存核销操作。

@chenshun 请出原型 @puttin 实现

**Comment by chenshun** [comment]
这是目前库存盘点统计表的原型：
[参考原型](https://projects.invisionapp.com/d/main#/console/292578/15723933/preview)

**Comment by chenshun** [comment]
原型调整如下：
- `库存汇总表`以目录的形式呈现，点击查看详情
- 库存详情中信息较多，所以全屏显示，暂时去掉左边菜单
- 首页中的`盘点`点击直接进入盘点界面

[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211680/preview)

**Comment by chenshun** [comment]
问题补充：目前商品的即时数量没有体现，如果用户不盘点，就不知道店里商品还有多少，建议在商品信息中加入商品数量。

**Comment by guanbo** [comment]
> 问题补充：目前商品的即时数量没有体现，如果用户不盘点，就不知道店里商品还有多少，建议在商品信息中加入商品数量。

商品即时数据就是盘点时的库存数量-出库+入库的数量。

**Comment by chenshun** [comment]
原型已经调整，主要是把盘点商品的列表方式改为弹出单品盘点的对话框形式。
[参考原型](https://projects.invisionapp.com/d/main#/console/292578/6211680/preview)

**Comment by guanbo** [comment]
@puttin 原型没有意见就请优先实现。

**Comment by chenshun** [comment]
现在的`差量`不能及时计算出来，要等到确定以后才可以，希望用户输完`实盘数量`就可以直接计算出。

**Comment by puttin** [comment]
需要说明的是 当前由`盘点`自动生成的`库存核销` 时间为`盘点时间`

而`盘点`数量统计是统计 `大于时间范围起始时间` 且 `小于等于时间范围结束时间` 时间段内的数据

即 `当前盘点`自动生成的`库存核销` 算在当前`盘点时间`内
