### ISSUE TITLE
新增雇员，列表不显示该数据，但是该雇员已经存在

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#474]
### 步骤
1. 进入管理系统，点击`雇员`
2. 点击`+`,输入会员名,`下一步`
3. 输入身份证与手机号，完成新增
### 结果

可以看到录入的雇员并没有出现在列表中，需要退出程序后才能看到
### 期望

创建完后就可以看到

**Comment by puttin** [comment]
已在 https://github.com/extensivepro/expropos/commit/fc77d6792daeffc5c8fd42dfc6c281b21b2a64fb#diff-9 修复
