### ISSUE TITLE
用双击扫码枪呼出键盘后，切到收银界面也会弹出键盘

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#479]
### 步骤
1. 进入POS管理系统，点击`进货`
2. 选择进货商品，当需要输入时双击扫码枪按键呼出键盘
3. `取消`进货，并切换到收银系统
### 结果

进入收银系统后，刚才呼出的键盘自动弹出
### 期望

不需要软键盘时，不会弹出

**Comment by guanbo** [comment]
这块扫描枪控制的暂时无解，只能再次双击收起。
