### ISSUE TITLE
首页中的会员总数与实际会员人数不同

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#481]
### 步骤
1. 进入POS管理系统
2. 点击`会员`，查看会员人数
3. 点击`首页`，查看`会员总数`
### 结果

可以看到首页中的`会员总数`与会员列表中的人数不同
### 期望

显示正确的会员人数

**Comment by puttin** [comment]
模拟器无法重现 需要在实际出问题的机器上看一下

**Comment by puttin** [comment]
首页统计的会员数量只统计了注册商店是当前商店的会员
而会员列表会显示商户下所有属于当前商店和未归属商店的会员

**Comment by guanbo** [comment]
这两者统一起来吧，首页也显示商户下所有的会员。

**Comment by chenshun** [comment]
> 这两者统一起来吧，首页也显示商户下所有的会员。

POS不应该是商店视角吗？为什么显示商户下所有会员？如果这样，会员分商户、商店级别还有什么意义？
#404

**Comment by guanbo** [comment]
原先考虑加盟店之间会员不通用，现在看来这样的设计有点多余。从目前来看还没有用户这样使用。会员的确是商户范围的，但可用被商店看到就显示统计总数吧，以免造成困扰。
