### ISSUE TITLE
进货时关于选择输入单价或是总价的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#482]
### 步骤
1. 进入POS管理系统
2. 点击`进货`，选择进货商品，输入进货数量
3. 点击`进货单价`，切换到`进货总价`
### 结果

无法切换，需要先输入`进货单价`才能切换
### 期望

可以自由选择是输入单价或是总价

**Comment by puttin** [comment]
做成这样是因为没有数量没法算单价总价

暂定改成没数量时只切换 但不修改金额
