### ISSUE TITLE
销售界面会员浏览选择

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#488]
## 需求

在销售开单的界面，客户希望通过会员按钮直接浏览所有会员，进行简单搜索定位到会员。适用，会员较少，知道名字但不一定知道电话或卡号的场景，例如服装批发档口。
## 任务

销售的会员按钮一直可以点击，打开会员浏览界面，要求：
- 顶部有搜索栏
- 按名字排序
- 扁平化设计，不贴图。

**Comment by chenshun** [comment]
> 顶部有搜索栏

现在的界面中无搜索栏

> 按名字排序

没有按照名字的首字母排序。

**Comment by guanbo** [comment]
暂时不提供搜索栏
