### ISSUE TITLE
挂靠设备无效需要删除应用

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#490]
## 问题

新设备启动后，在web平台挂靠设备到商户的商店下面。刷新设备无法同步商店的数据，显示还是未挂靠前的商店。重启无效。只有删除应用重新安装才有效。
## 期望

在挂靠以后做一次同步就可以将挂靠商店的数据同步到iPad设备上。

**Comment by chenshun** [comment]
建议在web端挂靠设备的地方，做一个提示用户如何查看自己设备序列号的提示。

**Comment by guanbo** [comment]
这个到crm上提个issue吧，在上面截屏帮助。
