### ISSUE TITLE
考虑通过浏览会员来选择会员身份的结算方式有两点不妥

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#491]
1. 使收银容易发生错误。现在选择会员直接进入该会员的结算界面，虽然简化了收银的步骤，但是也增加了发生错误的几率，如果会员人数规模较大，则同名同姓的概率非常多，收银员在收银时手忙脚乱加之粗心大意，很容易选错会员，并且毫不知情。
2. 不排除无聊的收银员没事查看各种会员账户，当发现某些会员长期不来消费，擅自用该会员的账户来为自己买单的情况。

**Comment by guanbo** [comment]
> 使收银容易发生错误。现在选择会员直接进入该会员的结算界面，虽然简化了收银的步骤，但是也增加了发生错误的几率，如果会员人数规模较大，则同名同姓的概率非常多，收银员在收银时手忙脚乱加之粗心大意，很容易选错会员，并且毫不知情。

确实存在上述情况，但同名的概率、收银员繁忙的情况都是我们自己的猜测。这块需求是用户提出来的，目前还不能断定我们的主力客群倾向那种情况。我的想法是有反馈，先按他们的意思放出去试试，等有人吐槽再调整。

> 不排除无聊的收银员没事查看各种会员账户，当发现某些会员长期不来消费，擅自用该会员的账户来为自己买单的情况。

这些情况是我们原先设计避免的场景，但从用户提到选择列表选择用户的需求来看，说明可能在客户资料和便利性上可能会选择后者。还是要看客户后续的反馈才好说。
