### ISSUE TITLE
希望在进货时可以调整商品售价

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#492]
我在进货时，遇到很多进货价格有变动的情况，要相应调整出售价格。但是现在进货时无法调整售价，需要到商品管理中调整，有点麻烦。
现实的零售店也应该会遇到这种情况，所以建议在进货时可以调整售价，让进货功能更加灵活。

**Comment by guanbo** [comment]
这块有待讨论，从银豹的做法来看有的商家是把定价权作为最重要的权力之一，不轻易的下放。我想把这块列入需要向用户调研的问题列表中。
