### ISSUE TITLE
会员账户既然可以充钱，是否有必要加入密码功能？？

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#494]
考虑会员可以往账户上充值，就有必要保障会员账户的财产安全。现在结算流程简化，会员结算时，对会员身份又没用验证，等到我们的POS普及后，少不了各种投机者。应该加入输入密码功能，会员用自己账户结账时需要输一次自己的密码。
用户在用这套系统时可能不能及时发现这点，总不能等到问题真的发生再等用户来反馈才解决吧！

**Comment by guanbo** [comment]
- 请设计加密环节，包括设置密码、输入密码、账户禁用（挂失）等。
- 对于小额支付例如200以内（含当日累计），可以免密码。
- 或者可以考虑和微信会员账单推送绑定的才可以免密码，否则全部要输入密码。
