### ISSUE TITLE
剩余库存不准确

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#495]
## 问题

客户原先是2.5.0版本，一直使用剩余库存查看。升级2.6.0以后查看剩余库存不准确，主要是上期库存没有统计，所以造成计算不准确。
## 解决

让用户进行盘点操作，计算出当前剩余的库存。或者对于没盘点记录的情况自动计算一次账面盘点的数据。

**Comment by puttin** [comment]
没看明白. 当前盘点功能无法实现吗?

**Comment by guanbo** [comment]
昨天站会提到可能是原先没有上传过，现在用udid注册了用户切换到另外一个账号上了。我会查下2.6的代码。
