### ISSUE TITLE
盘点生成的记录中，单品盘点数量存在为空的情况

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#497]
##### 前提条件

POS中有盘点记录
### 步骤
1. 进入POS管理系统，点击`盘点`
2. 选择一次盘点记录，点击打开详情
### 结果

可以看到盘点时没有盘点的商品，其`实盘数量`与`数量差异`都是空的
### 期望

针对没有盘点的商品，应该默认补全`实盘数量`与`数量差异`

**Comment by chenshun** [comment]
另外，生成的盘点记录，标题名应改成`盘点清单`，从而与`盘点`区分开，这样用户一眼就能知道自己是在盘点还是在查看盘点清单。

**Comment by puttin** [comment]
不是有时间段表示了么?
这个问题应该是 #496 造成的
