### ISSUE TITLE
销售数量、单价问题

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#50]
- [x] 商品销售数量可以输入0；
- [x] 数量超过库存时无提示；
- [ ] 单价如果不小心调整了，如何恢复至默认单价；
- [x] 流水记录中未体现折扣金额；

**Comment by guanbo** [comment]
下次最好拆分成多个issue,方便分别完成。

> 单价如果不小心调整了，如何恢复至默认单价

不提供恢复原价功能，删除该条商品重新录入。

> 流水记录中未体现折扣金额；

参见 #63
