### ISSUE TITLE
POS管理系统左侧菜单中需要加入菜单图标

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#507]
目前左侧菜单中缺少菜单图标，可以加入一些尽可能贴切菜单内容的图标。

**Comment by guanbo** [comment]
考虑先从[fontawesome-iOS](https://github.com/alexdrone/ios-fontawesome)中找一些配上，我已经引入到工程中了。

**Comment by puttin** [comment]
fontawesome 可能不适合左侧菜单 可能得考虑找 宗超

**Comment by puttin** [comment]
已通知宗超
