### ISSUE TITLE
由于库存记录采取每次都拉取数据的政策 本地未同步的数据无法显示

### ISSUE THREAD

**Issue by puttin** [extensivepro/expro-future-test#508]
相关 commit:
https://github.com/extensivepro/expropos/commit/c3e4d83327568f6b88d0de60e98d3c0e831a8248#diff-0

**Comment by guanbo** [comment]
已经在https://github.com/extensivepro/expropos/commit/42a17a95ebdf4fc31198b2c774a71c4b5db19149 中解决上述问题
