### ISSUE TITLE
自动同步获取数据时，希望加入可以取消同步的功能

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#525]
在登陆界面和查看`进出库`时，都会有一个同步的loading过程，因为当前的无线网络有问题，就会一直处于loading过程中，无法操作。建议loading可以取消，当loading长时间没有响应，也好让用户自己决定是否要继续等待。

**Comment by puttin** [comment]
绝大多数行为可以放后台同步

**Comment by puttin** [comment]
但是类似登陆界面 如果不等待同步完成 不能确保数据正确 @chenshun

**Comment by guanbo** [comment]
先调查从界面上取消的可能性，不要超过1个小时。
