### ISSUE TITLE
冲减储值

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#529]
## 需求

用户可能存在误操作，对客户进行了错误的储值。希望可以通过管理界面进行冲减操作。修正错。
## 任务
- 在管理界面中的会员管理中支持对会员储值的冲减功能。

**Comment by chenshun** [comment]
提现打印的小票上反馈的信息错误，例如：
账户金额`100`，提现`50`，打印的小票会显示：`充值金额50`，`充前余额-50`，`充后余额0`

**Comment by guanbo** [comment]
已经在https://github.com/extensivepro/expropos/commit/8d987708d3c360151e00230c9fdfe8e5ed35718a 修正
