### ISSUE TITLE
管理界面，新建的商品在商品列表中不显示，点击搜索再取消后新建的商品显示出来，原有的商品消失

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#53]
### 步骤
1. 点击`商品`
2. 新建一个商品，完善信息点击`创建`
3. 点击左上角`搜索`再点击`取消`
### 结果

刚才新建的商品显示在列表中，但是之前原有的商品消失
### 期望

`创建`完商品，列表就应该显示，并且搜索取消之后原商品应该还在

**Comment by puttin** [comment]
缘由是 @guanbo 在 https://github.com/extensivepro/expropos/commit/c09c5f374f83d1b86b08dc708ef039588ae17098#diff-38 光修改了首次显示的 未修改刷新和搜索的逻辑

**Comment by puttin** [comment]
管理商品这里的逻辑还是比较老 以后得重构
