### ISSUE TITLE
有弹出框时，如果系统休眠，再打开后不会退到登陆界面

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#537]
### 步骤
1. 进入管理系统，点击`销售流水记录`
2. 选择一条记录，查看`账单详情`（其他弹框同样有效，例如`进货`）
3. 锁屏
4. 重新打开
### 结果

打开后仍然处于系统中
### 期望

返回登陆界面，重新输密码

**Comment by puttin** [comment]
以下内容涉及到一些技术细节

---

因为都是 present 出来的, 没法同时 present 2个VC
想到两种解决方案
1. 弃用 `UISplitViewController` 自己实现一个
2. 建立第2个 `UIWindow` 作为 loginVC 的并设置更高 level 盖住第一个 `UIWindow`

**Comment by guanbo** [comment]
@puttin 我来看看吧，你搞定进货。

**Comment by puttin** [comment]
你这样的改法之前做的动作可能就丢失了 比如进货进到一半 锁屏 是显示了锁屏但是 进货的填写内容就丢失了

**Comment by chenshun** [comment]
**销售界面还存在BUG。**

### 步骤
1. 进入POS销售系统
2. 点击`销售`、`会员`，弹出会员列表的modal
3. 锁屏
4. 打开POS

### 结果

可以看到，刚才的会员modal出现在登陆界面

### 期望

modal消失

**Comment by guanbo** [comment]
> 你这样的改法之前做的动作可能就丢失了 比如进货进到一半 锁屏 是显示了锁屏但是 进货的填写内容就丢失了

先不考虑这样的情况。
