### ISSUE TITLE
进货初，会出现系统键盘与小数字键盘同时出现的情况

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#540]
##### 前提条件

连接CT10扫码枪，并且是呼出键盘的状态
### 步骤
1. 点击`进货`
### 结果

可以看到大键盘与小键盘同时存在，小键盘只显示一小半，感觉很奇怪
### 期望

保持始终只有一个输入键盘

**Comment by puttin** [comment]
暂时没发现在软件端控制软键盘弹出收缩的实现方式

**Comment by puttin** [comment]
#524

**Comment by puttin** [comment]
对于这种情况 暂定放弃数字键盘 只显示软键盘
