### ISSUE TITLE
出货存在的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#543]
现在的出货过程中存在两个问题：
- 出货是根据商品名称来定位商品的，但是商品名并不是唯一的，同样名字的商品因口味或是型号不同而编码不同，因此光靠`品名`无法确定是哪一件商品，要在选择商品的modal里加入商品编码；
- 选择商品的modal点击消失后就不会再出现了，应该可以点击之后重新出现。

**Comment by guanbo** [comment]
> 出货是根据商品名称来定位商品的，但是商品名并不是唯一的，同样名字的商品因口味或是型号不同而编码不同，因此光靠品名无法确定是哪一件商品，要在选择商品的modal里加入商品编码；

商品选择框面积很小，不建议加入很长的编码，可以考虑把型号加进来。

> 选择商品的modal点击消失后就不会再出现了，应该可以点击之后重新出现。

点击哪里重现商品列表？

**Comment by chenshun** [comment]
> 商品选择框面积很小，不建议加入很长的编码，可以考虑把型号加进来。

型号不是必填项，怕是有些同名商品没有型号。不过感觉这不重要，他可以自己去调整商品信息。

> 点击哪里重现商品列表？

点击需要输入的地方，例如商品名的input，这样适用于没选商品modal消失或是选错商品需要重新打开modal的情景。

**Comment by guanbo** [comment]
## 调整方案
- 在核销库存的商品选择界面中加入型号信息，帮助定位。
- 商品可以在选择以后通过点击商品名称弹出商品列表重新选择。
