### ISSUE TITLE
会员详情时，屏幕锁定，在登录时，界面卡死！

### ISSUE THREAD

**Issue by wangjing199408** [extensivepro/expro-future-test#544]
步骤

1.进入POS管理系统
2.点击会员
3.点击会员详情
4.屏幕锁定
5.再次登录

结果

界面卡死

期望

功能正常

**Comment by puttin** [comment]
界面卡死没遇到 闪退或者界面显示错误遇到过

原因是之前的旋转坑

**Comment by guanbo** [comment]
下个里程碑解决
