### ISSUE TITLE
实时库存中，商品型号处出现“null”字符

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#546]
### 步骤
1. 进入POS管理系统
2. 点击`盘点`、`实时库存`
### 结果

可以看到商品`麦芽糖`型号显示`（null）`
### 期望

正常

**Comment by puttin** [comment]
https://github.com/extensivepro/expropos/commit/e240743494d603d2fa5c10b4d79ca9ed500f1646
