### ISSUE TITLE
管理界面，销售商品汇总表中的“均价”与“销售额”均与实际销售不同

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#55]
销售商品汇总表中的`均价`与`销售额`显示值都是实际销售的一百倍。例如`4000`显示为`400000`

**Comment by puttin** [comment]
已在 https://github.com/puttin/expropos/commit/8baeee0a3dab8ed2a680a784502105266983885d#L1R260 处修复 
commit时忘记注释了
