### ISSUE TITLE
新增会员总是提示编码重复，并且会员会消失

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#550]
### 步骤
1. 进入POS管理系统
2. 点击`会员`，`+`
3. 完善会员资料，`创建`
4. 查看创建结果，查看该会员详情，再关闭
### 结果

编码没有重复，也会提示`会员编码重复`，查看详情后，返回列表发生该会员消失
### 期望

新增会员正常，会员不会消失

**Comment by puttin** [comment]
创建完成直接点击刷新也会消失

**Comment by puttin** [comment]
#536 引起
