### ISSUE TITLE
POS设置中的商店选择会使POS当前下挂的商店丢失，造成数据丢失

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#558]
### 步骤
1. 打开登陆界面，点击`设置`、`所属商店`
2. 点击`选择商店`，选择当前激活外的商店，例如iPad2中的`总店`
### 结果

报错`merchant fullName exist`,但是此时这个设备已经不属于当前激活的商店，之后进行的销售、进货等操作都不会上传，使数据丢失。
### 期望

不会出现类似没有上传的店铺，或者选择失败后不会使得设备下挂的商店消失。

**Comment by chenshun** [comment]
> 报错`merchant fullName exist`,但是此时这个设备已经不属于当前激活的商店，~~之后进行的销售、进货等操作都不会上传，使数据丢失。~~

数据并不会丢失，是时间问题。只会使得CRM设备管理列表中没有当前设备号。

**Comment by puttin** [comment]
由于初始化数据造成的问题.

该问题已经引发一些列问题, 建议尽快取缔.

**Comment by guanbo** [comment]
引入商店切换是重庆的用户无法找到自己的数据，因为自动上传店没有了。模式上我们需要再仔细考虑下。 @chenshun  @puttin @leonardean @tsq 我们可以开放的讨论一下。我初步的想法是：
- 保留自动上传数据的机制。
- 在iPad上挂靠商户的时候需要登录/注册。

**Comment by puttin** [comment]
我之前的观点是
种子数据保留但永不上传 一旦有新建商品雇员会员的时候提示注册新的商户商店等 全部成功后把原有离线的种子数据删除

**Comment by guanbo** [comment]
> 种子数据保留但永不上传 一旦有新建商品雇员会员的时候提示注册新的商户商店等 全部成功后把原有离线的种子数据删除

这样业务的复杂度会上升，涉及多个对象你都要人工判断。
