### ISSUE TITLE
会员详情存在的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#566]
查看会员详情的界面存在如下问题：
- 标题`会员详情`显示为`会员...`，应该正常显示
- 最下方`展开所有商店`只有点最右侧的箭头才会展开，而点中间的字无法展开，希望点字也可以展开。
- `展开所有商店`不知道是做什么的，有什么用，提示不够强烈，缺少目的性，建议调整，例如改为`去商店点餐`。

**Comment by guanbo** [comment]
> 最下方展开所有商店只有点最右侧的箭头才会展开，而点中间的字无法展开，希望点字也可以展开。

已经调整为点击整条展开

> 展开所有商店不知道是做什么的，有什么用，提示不够强烈，缺少目的性，建议调整，例如改为去商店点餐。

将会把点餐的入口独立出来，参考 #562 

> 标题会员详情显示为会员...，应该正常显示

@leonardean 请调查

**Comment by leonardean** [comment]
@guanbo 请求关闭

**Comment by guanbo** [comment]
> 标题会员详情显示为会员...，应该正常显示

从微信进入到 weixinWeb还是没有解决
