### ISSUE TITLE
登录收银界面，右上角身份的显示问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#57]
### 步骤
1. 打开POS，选择`收银员`身份进入收银界面
### 结果

可以看到界面右上角显示商店和身份的地方没有显示
### 期望

显示正常

---
### 步骤
1. 打开POS，选择`新业主`身份进入管理界面
2. 登出，再选择`收银员`身份进入收银界面
### 结果

可以看见右上角显示`新业主`
### 期望

应该显示`收银员`

**Comment by guanbo** [comment]
Fixed：https://github.com/extensivepro/expropos/commit/85e7ce135beb9fe1ebeb996fec282830375975ce
