### ISSUE TITLE
点菜时，点击左上角返回会使界面出现异常

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#570]
### 步骤
1. 进入商店点菜界面，选择一个品类进去点菜
2. 点击左上角`返回`
3. 再次`返回`，进入`会员详情`界面
### 结果

可以看到原本左上角多出一个按键
### 期望

正常

**Comment by guanbo** [comment]
@chenshun  给个截图，有图有真相。

**Comment by chenshun** [comment]
![image](https://cloud.githubusercontent.com/assets/3068259/2752024/6f098590-c8fa-11e3-929d-818099a1a3bc.png)
测试的时候，发现这类小问题的重现步骤不稳定，以上步骤多重复几次偶尔会出现。
还有一个类似问题是品类界面原本可以返回商店的`返回`按键消失，附图如下：
![image](https://cloud.githubusercontent.com/assets/3068259/2752034/3d54c342-c8fb-11e3-913e-673293a0603f.png)

**Comment by leonardean** [comment]
无返回的问题已解决，请求关闭。@guanbo
