### ISSUE TITLE
订单查询页面建议

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#577]
订单查询无内容时，已经有比较好的提示，希望可以继续美化该页面，另外建议增加直接跳转到订单的入口

**Comment by guanbo** [comment]
> 希望可以继续美化该页面

除直接跳转订餐界面外，还有什么具体的美化建议？

**Comment by xiaoyuxiong** [comment]
个人建议：以常规手机尺寸为标准，占据大部分屏幕范围，显示的友好一点，可以参考淘宝购物车为空时的页面，参考如下：
![getimgdata 1](https://cloud.githubusercontent.com/assets/2062648/2752095/696b9aa2-c8fe-11e3-94dc-685f180ed851.jpg)
