### ISSUE TITLE
登录管理界面时出现闪退

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#58]
### 步骤
1. 打开POS，选择`新业主`身份登录管理界面
### 结果

画面旋转出现一片黑色，然后程序闪退
### 期望

登录正常

（注：如果先选择`收银员`身份进入收银界面，再切换到管理界面可以正常登录，但是登出一次再选择进入管理界面，同样会出现该bug）

**Comment by guanbo** [comment]
目前的版本无法复现
