### ISSUE TITLE
点餐页面建议

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#580]
点餐页面时，希望可以点击上部中间（下图中的面食区域）部分切换大类，无须退回一步再重新选择。
![getimgdata 1](https://cloud.githubusercontent.com/assets/2062648/2752104/f419e97e-c8fe-11e3-81ef-f3b859876a63.jpg)

**Comment by xiaoyuxiong** [comment]
补充一下，如果面食区域可以点击，注意和其他的区别，提醒用户这里可以点击！

**Comment by leonardean** [comment]
那个区域无法点击，目前可行的方法是加一个带按钮的页脚，不过这样会使屏幕内所呈现的内容减少，有待斟酌
