### ISSUE TITLE
很多地方需要添加二次确认等建议

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#582]
按照使用习惯，某些地方需要添加二次确认，目前碰到的如下：
1.确认订单；
2.取消订单；
3.提交完订单后可增加个对话框，做个友好提示，并直接返回到会员查询主界面（个人建议，仅供参考，但是不建议目前的设置，还停留在菜单页面）；
4.订单目前有垃圾桶图标，但是不支持删除，如果可以，也需要添加二次确认；

**Comment by leonardean** [comment]
已完善，添加二次确认

**Comment by guanbo** [comment]
> 2.取消订单；

这块没有二次确认
