### ISSUE TITLE
支持店铺的快速定位

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#583]
会员详情页面，展开所有商店后，希望可以支持店铺的快速定位，比如在下图的右侧添加首字母的排列。
![getimgdata 1](https://cloud.githubusercontent.com/assets/2062648/2752202/d60709c2-c902-11e3-8b1a-a612461ea44c.jpg)

**Comment by guanbo** [comment]
> 会员详情页面，展开所有商店后，希望可以支持店铺的快速定位，比如在下图的右侧添加首字母的排列。

计划采用顶部搜索的模式来快速定位，因为右侧index适用的是数据相对固定的场景，找店这种场景更适合用直接搜索。
