### ISSUE TITLE
关于提交订单页面的bug

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#585]
订单提交页面，如下图，在总店里无论我选择什么，下方目前始终显示2份红烧牛肉面（使用过程中感觉是与红烧牛肉面始终保持默认2份有关，请核实）；另外建议出现订单页面时，上方的南京泛盈和返回按钮不显示，目前返回按钮点击无效。
![getimgdata 2](https://cloud.githubusercontent.com/assets/2062648/2752237/09a55828-c904-11e3-8614-95b8288c8b1b.jpg)

**Comment by guanbo** [comment]
> 另外建议出现订单页面时，上方的南京泛盈和返回按钮不显示，目前返回按钮点击无效。

这块微信暂时不提供接口隐藏，技术上无法实现。

> 订单提交页面，如下图，在总店里无论我选择什么，下方目前始终显示2份红烧牛肉面（使用过程中感觉是与红烧牛肉面始终保持默认2份有关，请核实）

估计还是cookie管理不当的问题，可能同#575，请 @leonardean 确认。

**Comment by leonardean** [comment]
cookie问题已解决
