### ISSUE TITLE
菜单确认界面

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#596]
在点餐完成后，菜单确认页面，如下建议：
1.商户旁边的图片建议使用商户自己的logo；
2.增加该笔消费的总价；,

**Comment by leonardean** [comment]
由于没有图片，暂时用公司的logo，
已添消费总价

**Comment by guanbo** [comment]
后端已经支持LOGO图片，但前端还是现实默认图片。
