### ISSUE TITLE
“库存流水记录”中显示信息与高保真不一致。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#6]
高保真中没有显示`商品`

**Comment by guanbo** [comment]
原型的需求做了一些调整，将原来商品型号分叉了。其中商品名称依旧，型号则是库存型号。

如无异议，请关闭。

**Comment by chenshun** [comment]
有个疑问，新建商品的时候显示的是`说明`，新建好的商品在`库存流水记录`中显示为`型号`，是不是`说明`=`型号`？如果是建议调整为统一说法。

**Comment by guanbo** [comment]
@puttin 请将新建SKU时候的说明改为型号。
