### ISSUE TITLE
有几个大类商品添加时的建议

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/expro-future-test#606]
现在水游城店已经有两个大类商品出现，操作体验改善建议：
1.菜单确认，在订单页面点击继续添加后，目前是回到最后确认菜单的页面，不方便添加其他大类商品，需考虑；
2.在添加过程中，如何跳转到其他大类商品进行选择需要斟酌；目前要退回，体验不佳；
3.现在返回又出现有默认数量的情况，没有清楚订单的时候（iPhone手机）；
.

**Comment by guanbo** [comment]
> 3.现在返回又出现有默认数量的情况，没有清楚订单的时候（iPhone手机）；

@leonardean 优先解决

> 1.菜单确认，在订单页面点击继续添加后，目前是回到最后确认菜单的页面，不方便添加其他大类商品，需考虑；
> 2.在添加过程中，如何跳转到其他大类商品进行选择需要斟酌；目前要退回，体验不佳；

后续解决

**Comment by leonardean** [comment]
> 3.现在返回又出现有默认数量的情况，没有清楚订单的时候（iPhone手机）；

这种机制是有意而为，除非用户提交或者清除订单，当前订单将一直保存以便用户下次进入该店后继续点单
