### ISSUE TITLE
微信前端计算搜周边的范围

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#609]
## 需求

目前的搜周边只是将有坐标的商店排在前列。并没有时间计算是否在搜索半径内。
## 方案
- 由客户端根据中心点距离搜索周边1公里范围的店铺
- 设计交互协议向后端发出查询在坐标象限内的店铺

**Comment by leonardean** [comment]
范围计算纯粹靠前端会比较不效率，会使的网页端下载过多的数据进行计算、排序。建议获取周边商店的时候带入用户坐标和搜索范围，这样在后台起码可以过滤掉经纬超过搜索范围的商店再给与返回

**Comment by guanbo** [comment]
- 这个问题优先级降低
- 计算怎么会下载过多数据？输入只要中心坐标和搜索半径？算法应该在js中下一次就OK
