### ISSUE TITLE
建议调整管理界面“设置”框左上角"登出"按钮的位置

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#61]
这个`登出`按钮一直困扰着我。
1. 当我进行完`账户设置`或是`商户设置`想要快速回到管理界面，就会忽略这个`登出`按钮，因此经常不小心点到他然后就登出去了。
2. 当我两只手同时操作这个POS，左手偶尔会碰到`设置`，然后弹出设置窗口，这时候因为是左手在操作，所以会习惯性去点左上角按钮，从而又忽略了这个是`登出`键，然后再重新选择身份登录进来，这样就打乱了之前的操作。

建议把`登出`和`完成`位置对调，或者把`登出`放在最下方设置成一个红色醒目的`登出`。

**Comment by guanbo** [comment]
> 建议把登出和完成位置对调，或者把登出放在最下方设置成一个红色醒目的登出。

同意。请 @puttin 调整
