### ISSUE TITLE
同步交易数据时加入手动同步按钮和选择时间段的设置

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#610]
关于同步交易数据，我是这样考虑的：
       在`销售流水记录`、`退货流水记录`等这些交易数据列表的右上角加入一个`载入`的按键，用户点击之后弹出选择的popover，可以选择载入`本周数据`、`本月数据`，就跟原来选择时间段查看数据一样，然后根据用户的选择从网络获取数据。

**Comment by guanbo** [comment]
- 还是放在一个地方同步全部的数据。
- 同步的位置可以考虑店长界面。
