### ISSUE TITLE
用户反馈期待在POS端能看到利润

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#611]
如题，用户很期待在POS上可以看到每段时间的利润统计。
真相在这里：
![image](https://cloud.githubusercontent.com/assets/3068259/2787215/f451c4ea-cb86-11e3-9c04-bf7e9d671a03.png)

**Comment by guanbo** [comment]
考虑周、月报表的形式展现经营情况，简单的考虑下面的统计
- 总进货成本和总销售额的差额
- 单品进货成本和单品销售的差额
- 先考虑在RMS上实现
