### ISSUE TITLE
交易数据是否要加入删除功能？

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#613]
用户反馈有一些没用的或者错误的交易数据希望可以删除，因为担心留在系统里怕影响日后的数据统计。
建议交易数据也加入删除功能。

**Comment by guanbo** [comment]
- 暂不提供交易撤销的功能，影响比较大。
- 可以说服用户小概率的时间可以走退货流程，会有影响统计的结果，但影响不大。
