### ISSUE TITLE
输入错误数据时没有及时反馈 用户不知道发生了什么

### ISSUE THREAD

**Issue by puttin** [extensivepro/expro-future-test#64]
#39

暂定 `给错误UITextField加红色边框`

**Comment by guanbo** [comment]
你这个错误数据在什么场景下？修复后怎么验证？

**Comment by puttin** [comment]
> 你这个错误数据在什么场景下？

错误数据就是新建商品库存等修改商品会员等信息时输入的不正确的数据(比如错误的邮箱,错误的手机号)

这种情况理应让用户清楚哪里有问题, 为何不能保存, 为何不能新建

> 修复后怎么验证？

修复后可以在各个出错的地方 有意输入错误的信息 看是否明白为何流程不能继续

相关的Issues:
1. https://github.com/extensivepro/expropos/issues/42
2. #9 
3. #10 
4. #22 
5. #29 
6. #30 
7. #85

**Comment by puttin** [comment]
@guanbo @chenshun 要不要考虑使用 类似 https://github.com/chrismiles/CMPopTipView 的方式实现提示?
当前只实现了加红框 有些部分用户不明白哪里出错了

**Comment by guanbo** [comment]
可以，动作快点。晚上10点我要上架。
