### ISSUE TITLE
有销售数据，但是销售统计中并没有体现

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#642]
![image](https://cloud.githubusercontent.com/assets/3068259/2899087/e793e4f4-d5ae-11e3-8d41-8e098b303f5d.png)

![image](https://cloud.githubusercontent.com/assets/3068259/2899091/f13cf91e-d5ae-11e3-8502-a3641934569a.png)

**Comment by guanbo** [comment]
这个是因为泛商汇的错误，订单转交易的时候没有生成结算项目cashSettlement，已经修复。
