### ISSUE TITLE
微信电商商品详情页

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#650]
## 需求

商品详细情况的页面，有一张主图详细介绍、价格。
## 方案

参考微团购的详情页面

**Comment by leonardean** [comment]
也就是说下单不在商品展示列表那，而是点击商品展示列表后进入下一层界面(单品详情界面), 然后在那个页面进行商品的订购？（如选择数量，加入购物车）

**Comment by guanbo** [comment]
- 对不在列表展示界面中下单，在详情中下单。
- 暂时不提供查看图文详情。
