### ISSUE TITLE
销售商品时，点击确认会默认选择出售商品

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#67]
### 步骤
1. 点击`销售`
2. 点击`确认`
### 结果

左边交易账单中会自动出现商品
### 期望

点击`确定`不会跳出默认商品

**Comment by guanbo** [comment]
- 不输入的情况下点击`确认`不会登记上牌
- 自动提示框显示的适合会默认选择第一个商品，这样是为方便商店录入设计的。

**Comment by chenshun** [comment]
不输入的情况下点击`确认`也会有商品登记出售

**Comment by chenshun** [comment]
刚才确认了一下，如果首次登入收银界面，不输入点`确认`不会登记出售商品，但是当你输入过后，不管是否取消或是结算完成，下次`销售`即使没有任何输入点击`确定`也会带出之前出售的商品。

**Comment by guanbo** [comment]
OK，确认问题。
