### ISSUE TITLE
泛商汇商户信息支持匿名获取

### ISSUE THREAD

**Issue by leonardean** [extensivepro/expro-future-test#671]
@guanbo

**Comment by guanbo** [comment]
已经在 https://github.com/extensivepro/expro-future/commit/b654335c54f24ad0ad56da998202eed6b720a8c8 中解决。

我本意是让你在关联的issue #661 中说下就可以了

**Comment by guanbo** [comment]
已经在 https://github.com/extensivepro/expro-future/commit/b654335c54f24ad0ad56da998202eed6b720a8c8 中解决。

我本意是让你在关联的issue #661 中说下就可以了
