### ISSUE TITLE
"购物车"中商品的显示问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#672]
- `－`与`+`中间的数字要居中；
- 右侧的`份`字建议去掉，因为每种商品单位都不一样，还可以腾出空间。如不去掉，需要完整显示；
- 最右侧`删除`的button建议改成一个垃圾桶的图标，黑色的大按键实在不好看。

**Comment by guanbo** [comment]
> －与+中间的数字要居中；
> 右侧的份字建议去掉，因为每种商品单位都不一样，还可以腾出空间。如不去掉，需要完整显示；

已经修复

> 最右侧删除的button建议改成一个垃圾桶的图标，黑色的大按键实在不好看。

还是保留用文字，比较明确。
