### ISSUE TITLE
关注公众号后，得到的会员需要优化

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#673]
![image](https://cloud.githubusercontent.com/assets/3068259/2983822/8bec771a-dc2a-11e3-8c8e-891b65feb65f.png)
如上图，会员名与编码显示的太粗糙了，用户接受不了。

**Comment by guanbo** [comment]
- 目前已经支持修改名字。
- 对于没有手动修改过名字的，采用第一次的收获地址名字作为用户名。 @leonardean 实现。

**Comment by guanbo** [comment]
现在仅支持服务号可以在后台获取用户的名字。将调整关注会员的机制。
