### ISSUE TITLE
顾客下单到选择付款的步骤应该变更

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#676]
现在整个流程是这样的：
1. 顾客选择商品，加入购物车
2. 进入购物车，选择`结算`
3. 点击`下单`，提示`下单已完成`
4. 去`待付款订单`找到刚才的订单，查看详情
5. 最下方`我要付款`选择付款方式
这个流程可以改善，顾客在点击`下单`时就应该可以直接选择付款方式,然后完成一笔订单。
否则在进行到第三步时，很可能认为整个操作流程已经结束了。

**Comment by guanbo** [comment]
> 1. 最下方我要付款选择付款方式
>    这个流程可以改善，顾客在点击下单时就应该可以直接选择付款方式,然后完成一笔订单。
>    否则在进行到第三步时，很可能认为整个操作流程已经结束了。

上述流程只是应付早上客户演示的临时措施，请 @chenshun  重新流程。 @leonardean 实现

**Comment by chenshun** [comment]
[微信顾客购物流程时序图](https://projects.invisionapp.com/d/main#/console/292578/24588845/preview)
请preview
