### ISSUE TITLE
iPad Pos 新增加的库存记录看不到

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#677]
### 步骤
1. 点击左侧菜单`进出库`
2. 点击`+`增加一批库存
3. 查看库存记录
### 结果
- 进行第一步时，看不到加载动画；
- 得到的库存记录商品信息都是空白；
- 刚才新增的库存记录在列表中看不到
### 期望
- 加入载入动画
- 相关issue #678 
- 可以看到新增的库存记录

**Comment by puttin** [comment]
现在的方式造成的就是未同步或者未同步成功的 直接不显示了
可以刷新一下 同步成功的应该就能显示出来

**Comment by chenshun** [comment]
新下的版本，在Pad上始终无法显示，包括会员的交易数据、商品进出库记录，只有普通顾客的销售数据正常显示。
另外在同步各个交易记录的时候没有loading动画。。。

**Comment by puttin** [comment]
loading 动画另提一个
