### ISSUE TITLE
二维码墙业务流程设计

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#682]
设计扫码二维下单的业务流程，绘制时序图。
- 商家在RMS平台新增商品，并导出二维码以商品名称作为文件名。
- 制作包含二维码和商品图片的海报，供消费者扫码。（系统外运作）
- 微信扫码下单
  - 已经关注过公众号的顾客直接进入到商品详单。
  - 没有关注过的用户先关注公众号成为会员，然后再进入商品详情页面。
- 支付宝付款
- 后台确认付款后，门店打印出品单，准备交付商品。

**Comment by chenshun** [comment]
[下单时序图](https://projects.invisionapp.com/d/main#/console/292578/24588845/preview)
请preview

**Comment by guanbo** [comment]
已经评论。

**Comment by chenshun** [comment]
- [这个是顾客扫码购物时序图](https://projects.invisionapp.com/d/main#/console/292578/24696834/comments)
- [这个是支付流程时序图](https://projects.invisionapp.com/d/main#/console/292578/24588845/comments)

可能还存在一些问题，请preview
rename之后原来的评论已经不是那张图了，所以都标记完成了。

**Comment by guanbo** [comment]
- 扫码时序图OK了。
- 支付流程有一些评论。

**Comment by chenshun** [comment]
支付流程已经更新，把三种方式分开了
- [支付流程时序图](https://projects.invisionapp.com/d/main#/console/292578/24588845/preview)

**Comment by guanbo** [comment]
已经做了评论
