### ISSUE TITLE
商品详情页直接访问和分享

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#684]
## 需求
- 方便直接展现到单品，需要支持商品详情页直接方案并开始下单。
- 适用好友分享商品链接或类似二维码直接定位到单品的情况。
## 方案
- 支持商品带查询参数的方式直接显示商品。
- 分享的时候在地址包括商品编码参数，确保能直接打开。

**Comment by leonardean** [comment]
在公众号为服务号以及有高级接口的前提下可以实现。据了解微信现有的`发送给好友`以及`分享至朋友圈`功能都是针对静态页面，如某个页面是通过某个公众号发出的view打开，则分享该页面给好友的时候会发送一个view，其title和图片都来自原公众号的view。如果待分享页面不是直接来自于某公众号的view，比如深层链接，则分享方式为分享静态链接，无图片。 目前可以做到的是通过链接中带有itemID和merchantID定位到商户以及商品，如需进行下单操作则需要OAuth验证取得openID和身份信息(此时该用户甚至还不是会员，因为没有关注)。 当前受限于服务号，不得已将openID和ticket带入Url，单纯分享商品则会使得被分享用户以分享用户身份打开链接和后续操作

**Comment by guanbo** [comment]
> 目前可以做到的是通过链接中带有itemID和merchantID定位到商户以及商品，如需进行下单操作则需要OAuth验证取得openID和身份信息(此时该用户甚至还不是会员，因为没有关注)

就是这个意思，我已经让即刻咖啡申请服务号高级接口了

**Comment by guanbo** [comment]
@leonardean 分享以后图片、标题、简介的问题必须要解决。
