### ISSUE TITLE
商品库存为空时，要能让微信端的顾客看到，并且不能加入购物车

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#689]
如题，否则顾客下了单也付了款，商家发现库存空了就难堪了。

**Comment by guanbo** [comment]
- 需要实时统计库存
- 实时库存是建立在每天库存map reduece的基础上进行。

**Comment by guanbo** [comment]
https://github.com/extensivepro/expro-future/commit/b515d232b321792ddf7a5adaa115d088dc355fda

已经在上面commit中实现后端支持，请 @leonardean 实现前端商品列表和详情页的库存情况以及销量情况。
