### ISSUE TITLE
订单中是否要加入“邮费”功能？

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#691]
部分快递不支持`到付`功能，岂不是卖家要承担运费？
如果选择`货到付款`，或者购买者拒收时，商家要承担运费的损失。
部分商家喜欢多卖包邮搞促销。

**Comment by guanbo** [comment]
> 部分快递不支持到付功能，岂不是卖家要承担运费？

在商户中设置是否支持到付的开关，web前端根据商户的属性来显示是否到付。

> 如果选择货到付款，或者购买者拒收时，商家要承担运费的损失。

没有用过到付， @leonardean 出来说说

> 部分商家喜欢多卖包邮搞促销。

这块需要引入物流模板才能解决。

@chenshun 我们目前应该与线上的传统电商差异化竞争，立足本地话电商和服务。物流方面可以先设计简单，全部先按包邮处理。
