### ISSUE TITLE
POS 在编辑会员邮箱时，左侧储值金额会发生变化

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#693]
### 步骤
1. 进入POS管理系统，点击会员，查看详情
2. 点击`编辑`，修改会员的电话或邮箱
3. 点击`保存`
### 结果

可以看到会员左侧`储值金额`发生变化，下方的`储值金额`记录也会产生变化
### 期望

不会变

**Comment by puttin** [comment]
无法重现
