### ISSUE TITLE
泛商汇微信会员关联

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#698]
- 利用手机定位到已有的会员，设置当前微信openID与会员关联。
- 关联成功后删除微信网关因为会员关注而自动创建的会员。

**Comment by chenshun** [comment]
重新关注后，查看`我的会籍`，发现名片中的姓名并非是我的会员名，而是重新创建的一位会员，似乎没有与已有的会员关联上。

**Comment by guanbo** [comment]
- 关注后如果openID不存在则创建一个新会员。
- 在微信webapp里面利用手机号码在将这个会员和线下会员关联 参考 #697 ，成功以后删除原来创建的会员。
