### ISSUE TITLE
POS 编辑两个会员会导致无限同步

### ISSUE THREAD

**Issue by puttin** [extensivepro/expro-future-test#699]
怀疑原因是 更新会员 返回的 json 里面没有 OwnerID 导致冗余的 account

从而造成认为实际上更新成功的 member 被修改 然后不断同步

怀疑 #693 是这个问题引起的

**Comment by guanbo** [comment]
https://github.com/extensivepro/expro-future/commit/1411bc51ef3010a792a65b14d8dff410959c7d84
加入更新会员时候返回ownerID

@chenshun

**Comment by puttin** [comment]
@chenshun 测试的时候可以尝试打开 Xcode 打开 log

然后修改 freedom 和 王延之 两名会员的邮箱
上周这样修改会看到不断的 log 显示不断地同步

---

@guanbo 
account 冗余的问题并没有解决掉
确定重现步骤:
1. 还原模拟器
2. 运行程序
3. 管理界面会员管理
4. 新建会员 编码 1 姓名 q 使用 CoreDataPro 或类似工具查看表现正常
5. 新建会员 编码 2 姓名 w 开始冗余

预计原因是 先 mapping 了 account 发现找不到对应的 ownerID 于是建立了一个新的 account 然后 mapping 了 member

当初使用 ownerID 是因为 gid 是服务端生成的 直接用 gid 也会冗余
