### ISSUE TITLE
商家无法决定新建的会员是商户级别还是商店级别的

### ISSUE THREAD

**Issue by puttin** [extensivepro/expro-future-test#70]
可以考虑设置个开关来选择, 方案:
1. 每次新建会员都要选择
2. 在本地用户设置或是其他位置设置后, 每次新建都默认选择设置好的
3. 其他

**Comment by guanbo** [comment]
> 在本地用户设置或是其他位置设置后, 每次新建都默认选择设置好的

在设置中加入默认会员级别，default是商户级别。

**Comment by puttin** [comment]
> 在设置中加入默认会员级别，default是商户级别。

在用户设置 的`商户商店` section 和 `服务条款` section 之间加一个`其他设置`?

**Comment by guanbo** [comment]
可以。
