### ISSUE TITLE
订单号需要唯一不重复

### ISSUE THREAD

**Issue by leonardean** [extensivepro/expro-future-test#702]
另外，最好是无明显规律的。当密钥被攻破时，攻击者伪造大量未使用的订单号（不少网站的订单号都是递增的纯数字，并公开给用户，且很容易推测到后面的数字），向支付宝请求订单，直到超时。由于商家对此并不知情（回调地址和通知地址均篡改掉），其他用户下单时假如商家用了被伪造过的订单号，就可能被支付宝认为提交了重复订单，结果支付失败。

**Comment by guanbo** [comment]
> 当密钥被攻破时

这种情况暂不考虑，你看到很多这样的案例吗？

**Comment by guanbo** [comment]
@leonardean 现在调整为timesince1970s+三位顺序循环数字
