### ISSUE TITLE
从“我的会籍”右滑查看主菜单时，订单显示的数量不会变更

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#703]
##### 前提条件

账号下存在`待付款订单`
### 步骤
1. 将`代付款订单`取消
2. 返回微信对话界面，查看`我的会籍`
3. 右滑查看主菜单
4. 点击`待付款订单`，查看
### 结果

可以看到菜单中显示的数量与点击进去查看的订单数量不相符，因为菜单中显示的数量没有更新
### 期望

显示实际订单数量

**Comment by leonardean** [comment]
在我手机上已没有这种情况出现，取消代付订单后，菜单显示的订单数量会更新，有待验证
