### ISSUE TITLE
下单完成后，自动跳转到“待付订单”总是刷新不出来

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#704]
### 步骤
1. 点击`抢购`
2. 选择一件商品，`直接结算`
3. 点击`结算`、`允许授权`
4. 点击`下单`，选择`货到付款`、`OK`
### 结果

系统跳转到`待付订单`，一直处于加载中
### 期望

正常跳转

**Comment by leonardean** [comment]
目前我手机上已不存在这个问题，有待验证
