### ISSUE TITLE
POS-用户需求 针对没有编码的商品，销售时可以通过字母来调取

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#707]
用户提出，自己经营的很多商品没有数字编码，这些商品在销售时，无法快速定位，几千个品类，让店员记数字不现实，希望可以通过字母来调取货品。

**Comment by chenshun** [comment]
@guanbo 现在收银时可以输入字母，但是在登记商品的时候因为只有小键盘，所以仍然无法用字母作为助记码，应该把登记、编辑助记码地方的小键盘换成全键盘。

**Comment by guanbo** [comment]
字母缩写是根商品名绑定的，修改商品名字的时候自动调整首字母缩写。与数字助记码无关。
