### ISSUE TITLE
POS-用户需求 多种商品一起销售，不能给不同的商品输入不同的折扣

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#710]
用户提出，希望多种商品一起销售时，可以针对不同商品输入不同折扣。
考虑是否可以给商品加一个`折扣`的属性，在进货登记时就直接设定，这样销售时就不用输折扣了。

**Comment by guanbo** [comment]
单品折扣在客户端调整需要原型考虑清楚，改动的地方不少。需要全面的考虑。
