### ISSUE TITLE
微信会员关联线下后详情信息不对

### ISSUE THREAD

**Issue by guanbo** [extensivepro/expro-future-test#714]
## 步骤
- 关注服务号南京泛盈
- 底部菜单->会员中心->会员中心
- 关联电话号码
## 预期
- 正确显示储值余额
- 正确显示累积积分
- 正确显示累计积分
## 实际
- 余额的单位显示为分，应显示元
- 累积积分0，实际为postPoint：4000
- 累计积分没有，实际为postTotalPoint：4000

**Comment by guanbo** [comment]
@leonardean 请参看官方blog把commit message写正确，否则总是不能自动关闭。

下面这个编号后面要和说明有空格：

> extensivepro/expro-future#389会员关联成功提示以及刷新数据, close extensivepro/expro-future-test#714微信会员关联线下后详情信息不对

**Comment by chenshun** [comment]
缺少关联失败的提示，比如输入一个不存在的号码，应该提示`关联失败`而不是`已完成`。
