### ISSUE TITLE
会员关联存在的问题——合并关联后账户信息和交易记录

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#715]
- 会员关联失败缺少提示，不知道有没有关联上
- 关联成功后应该刷新`我的会籍`，看到新的信息
- 关联后会删除原本的会员资料，应该告知用户。两个账户内的积分、储值是否应该累加？

**Comment by guanbo** [comment]
> 会员关联失败缺少提示，不知道有没有关联上
> 关联成功后应该刷新我的会籍，看到新的信息

同 #714 

> 关联后会删除原本的会员资料，应该告知用户。两个账户内的积分、储值是否应该累加？

可以考虑合并账户和相关的交易记录。已修改标题
- 累计账户储值和积分
- 将微信自动创建账户的交易和订单关联到线下的会员ID上。
