### ISSUE TITLE
管理界面，设置中的“服务条款”、“关于我们”都没有

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#74]

**Comment by puttin** [comment]
`服务条款` 和 `关于我们` 显示什么内容?

**Comment by guanbo** [comment]
- [x] 服务条款将给一个txt，https://github.com/extensivepro/expropos/commit/5b3acd157028dc7b823557173ee8858aee2b6f65
- [x] 关于我们放一张泛卡汇LOG，下面是联系方式，稍后我上传原型。
