### ISSUE TITLE
希望在“流水”中可以查看到退货账单。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#77]
可以通过`退货单`或`交易号`查看到退货单的详细信息

**Comment by guanbo** [comment]
设计原型

**Comment by chenshun** [comment]
用户通过交易号查询到流水账单。商品退货之后，会显示在该流水账单的下方，点击之后即可查看相关退货帐单。
[参考原型](https://projects.invisionapp.com/d/main#/console/292578/10137221/preview)

**Comment by chenshun** [comment]
相关issue:https://github.com/extensivepro/expro-future-test/issues/180

**Comment by guanbo** [comment]
@puttin 是否能在本周版本中完成？如果不能则放到下个版本。
