### ISSUE TITLE
管理界面，关于各个列表上面的“搜索”功能

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#78]
输入查询条件，当查询出相应的结果后，我想要隐藏掉搜索框同时还可以继续查看刚刚查询出的信息。而目前的情况，查询出结果后，搜索框仍然显示着，无法隐匿掉。

**Comment by guanbo** [comment]
这种情况应该不合适将搜索栏隐藏，因为搜索栏在这类还表征了过滤条件。不建议建议这样调整。

**Comment by puttin** [comment]
但@chenshun 提及一点就是搜索时必须点击键盘的隐藏键才能缩小键盘, 点击tableView部分不会隐藏 这点要不要调整?

**Comment by guanbo** [comment]
放到下个版本吧
