### ISSUE TITLE
会员列表会多出会员信息，并且可以添加空资料会员，空资料会员在列表中显示错误。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#8]
每进入一次收银界面，再回到商店界面，会员列表就会多出一条会员信息。并且添加会员可以添加一个资料为空的会员，添加出的空资料会员在列表中显示错误。

**Comment by puttin** [comment]
@guanbo 为何现在的会员也是挂在商户下的?

**Comment by guanbo** [comment]
- 会员有两种范围的，商户和商店。区分的方式是shop为nil则是商户会员。
- 商户会员在任意商店有效，商店会员只能在本地有效。
