### ISSUE TITLE
管理界面，关于创建商品时“商品编码”的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#85]
- 两个不一样的商品可以用一模一样的商品编码。
- 商品编码可以是以0开头的字符串，例如`00008`，这种情况的商品在销售时无法准确查询到。

**Comment by guanbo** [comment]
> 两个不一样的商品可以用一模一样的商品编码。

商品编码在商户范围内必须唯一

> 商品编码可以是以0开头的字符串，例如00008，这种情况的商品在销售时无法准确查询到。

在 #87 中解决

**Comment by puttin** [comment]
该Issue与 extensivepro/expropos#42 相关
