### ISSUE TITLE
管理界面，付款流水记录列表中的“储值消费”与“走入”显示的是英文

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#86]
点击`付款流水记录`，列表中可见。

**Comment by puttin** [comment]
1. `储值消费` 处储值消费类型的显示为英文是因为 管理页面 根据 交互协议 使用的 `prepay` 而实际POS处使用的是 `member`
2. `走入` 顾客显示为英文是因为 @guanbo 在 https://github.com/extensivepro/expropos/commit/834a7bfff90591e69d0bba49589c68b4c3e6b3af#L10R90 处把字段给删了
