### ISSUE TITLE
退货的时候，原本结算时的折扣金额会变成现金退给顾客

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#90]
### 步骤
1. 点击`流水`，输入一个交易流水号点击`确认`（该交易账单中需要有`折扣金额`）
2. 选择交易账单中的商品，点击`退货`
### 结果

可以看到账单中的`折扣金额`与`折扣比率`变成了`0`，`现金`的数额增加。
### 期望

退货正常。

**Comment by guanbo** [comment]
将调整为退货的时候，按销售折扣比率抵扣退款。自动生成退货折扣。
