### ISSUE TITLE
销售结算，选择会员储值时，输入的金额可以大于会员账户的余额

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#91]
### 步骤
1. 点击`销售`，输入商品编码选择销售商品
2. 点击`结算`
3. 点击`选择会员`，输入会员编码`确认`
4. 再点击`选择会员`，点击`现金付款`切换到`会员储值`
5. 输入大于会员账户余额的数字，点击`确认`
### 结果

账单中的`余额`显示为负数
### 期望

当储值余额不足，不能支付

**Comment by guanbo** [comment]
当余额不足时候，有多少结算多少。

**Comment by chenshun** [comment]
现在会员储值账户的`余额`又到了`找零`里面。

**Comment by chenshun** [comment]
销售结算时，选择`会员储值`付款，输入金额后，`实收金额`也会显示出与他一样数目的金额，而事实上我并没有输入`现金付款`。

**Comment by guanbo** [comment]
这个是正常的，实收金额是现金和储值的和。
