### ISSUE TITLE
库存汇总表中的信息不够详细且不准确

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#93]
建议把管理界面中的`库存汇总表`做的像`销售商品汇总表`一样详细、直观。两点理由：
- 当一种商品有多种型号的库存时，它不能完全的展现出来，这样用户就不能很直观的看出哪些型号的商品已经缺货。
- 该表中的`售价`是各种不同型号商品的均价，这样的信息反应给用户，用户就会觉得不准确，因为用户本身并没有开出这样的`售价`。

**Comment by guanbo** [comment]
以[更新的原型](http://invis.io/TUFMLGD2)为准
