### ISSUE TITLE
"销售流水记录"列表只能看到“销售”的交易信息，“退货”、“充值”不显示

### ISSUE THREAD

**Issue by chenshun** [extensivepro/expro-future-test#99]
高保真中的列表，从它的`类型`可以看出是`销售`或是`退货`，但在POS的管理界面，`类型`中显示的是笼统的`交易`，并且退货与充值记录均不显示。

**Comment by puttin** [comment]
`销售流水`只能显示`销售`的相关信息
`退货`和`充值`属于`账单`层次 不应在`销售流水记录`中显示
